// Code generated by ent, DO NOT EDIT.

package usdtpaymentintent

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the usdtpaymentintent type in the database.
	Label = "usdt_payment_intent"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOrderID holds the string denoting the order_id field in the database.
	FieldOrderID = "order_id"
	// FieldOutTradeNo holds the string denoting the out_trade_no field in the database.
	FieldOutTradeNo = "out_trade_no"
	// FieldProviderInstanceID holds the string denoting the provider_instance_id field in the database.
	FieldProviderInstanceID = "provider_instance_id"
	// FieldAddress holds the string denoting the address field in the database.
	FieldAddress = "address"
	// FieldNetwork holds the string denoting the network field in the database.
	FieldNetwork = "network"
	// FieldTokenContract holds the string denoting the token_contract field in the database.
	FieldTokenContract = "token_contract"
	// FieldAmountUsdt holds the string denoting the amount_usdt field in the database.
	FieldAmountUsdt = "amount_usdt"
	// FieldRate holds the string denoting the rate field in the database.
	FieldRate = "rate"
	// FieldBaseRate holds the string denoting the base_rate field in the database.
	FieldBaseRate = "base_rate"
	// FieldPremiumPercent holds the string denoting the premium_percent field in the database.
	FieldPremiumPercent = "premium_percent"
	// FieldRateSource holds the string denoting the rate_source field in the database.
	FieldRateSource = "rate_source"
	// FieldRateQuotedAt holds the string denoting the rate_quoted_at field in the database.
	FieldRateQuotedAt = "rate_quoted_at"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldMatchedTxHash holds the string denoting the matched_tx_hash field in the database.
	FieldMatchedTxHash = "matched_tx_hash"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the usdtpaymentintent in the database.
	Table = "usdt_payment_intents"
)

// Columns holds all SQL columns for usdtpaymentintent fields.
var Columns = []string{
	FieldID,
	FieldOrderID,
	FieldOutTradeNo,
	FieldProviderInstanceID,
	FieldAddress,
	FieldNetwork,
	FieldTokenContract,
	FieldAmountUsdt,
	FieldRate,
	FieldBaseRate,
	FieldPremiumPercent,
	FieldRateSource,
	FieldRateQuotedAt,
	FieldStatus,
	FieldMatchedTxHash,
	FieldExpiresAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// OutTradeNoValidator is a validator for the "out_trade_no" field. It is called by the builders before save.
	OutTradeNoValidator func(string) error
	// ProviderInstanceIDValidator is a validator for the "provider_instance_id" field. It is called by the builders before save.
	ProviderInstanceIDValidator func(string) error
	// AddressValidator is a validator for the "address" field. It is called by the builders before save.
	AddressValidator func(string) error
	// DefaultNetwork holds the default value on creation for the "network" field.
	DefaultNetwork string
	// NetworkValidator is a validator for the "network" field. It is called by the builders before save.
	NetworkValidator func(string) error
	// TokenContractValidator is a validator for the "token_contract" field. It is called by the builders before save.
	TokenContractValidator func(string) error
	// AmountUsdtValidator is a validator for the "amount_usdt" field. It is called by the builders before save.
	AmountUsdtValidator func(string) error
	// RateValidator is a validator for the "rate" field. It is called by the builders before save.
	RateValidator func(string) error
	// BaseRateValidator is a validator for the "base_rate" field. It is called by the builders before save.
	BaseRateValidator func(string) error
	// PremiumPercentValidator is a validator for the "premium_percent" field. It is called by the builders before save.
	PremiumPercentValidator func(string) error
	// RateSourceValidator is a validator for the "rate_source" field. It is called by the builders before save.
	RateSourceValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// MatchedTxHashValidator is a validator for the "matched_tx_hash" field. It is called by the builders before save.
	MatchedTxHashValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the USDTPaymentIntent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByOrderID orders the results by the order_id field.
func ByOrderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrderID, opts...).ToFunc()
}

// ByOutTradeNo orders the results by the out_trade_no field.
func ByOutTradeNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutTradeNo, opts...).ToFunc()
}

// ByProviderInstanceID orders the results by the provider_instance_id field.
func ByProviderInstanceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderInstanceID, opts...).ToFunc()
}

// ByAddress orders the results by the address field.
func ByAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAddress, opts...).ToFunc()
}

// ByNetwork orders the results by the network field.
func ByNetwork(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNetwork, opts...).ToFunc()
}

// ByTokenContract orders the results by the token_contract field.
func ByTokenContract(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokenContract, opts...).ToFunc()
}

// ByAmountUsdt orders the results by the amount_usdt field.
func ByAmountUsdt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmountUsdt, opts...).ToFunc()
}

// ByRate orders the results by the rate field.
func ByRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRate, opts...).ToFunc()
}

// ByBaseRate orders the results by the base_rate field.
func ByBaseRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBaseRate, opts...).ToFunc()
}

// ByPremiumPercent orders the results by the premium_percent field.
func ByPremiumPercent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPremiumPercent, opts...).ToFunc()
}

// ByRateSource orders the results by the rate_source field.
func ByRateSource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRateSource, opts...).ToFunc()
}

// ByRateQuotedAt orders the results by the rate_quoted_at field.
func ByRateQuotedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRateQuotedAt, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByMatchedTxHash orders the results by the matched_tx_hash field.
func ByMatchedTxHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMatchedTxHash, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
