// Code generated by ent, DO NOT EDIT.

package usdtpaymentintent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldLTE(FieldID, id))
}

// OrderID applies equality check predicate on the "order_id" field. It's identical to OrderIDEQ.
func OrderID(v int64) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldEQ(FieldOrderID, v))
}

// OutTradeNo applies equality check predicate on the "out_trade_no" field. It's identical to OutTradeNoEQ.
func OutTradeNo(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldEQ(FieldOutTradeNo, v))
}

// ProviderInstanceID applies equality check predicate on the "provider_instance_id" field. It's identical to ProviderInstanceIDEQ.
func ProviderInstanceID(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldEQ(FieldProviderInstanceID, v))
}

// Address applies equality check predicate on the "address" field. It's identical to AddressEQ.
func Address(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldEQ(FieldAddress, v))
}

// Network applies equality check predicate on the "network" field. It's identical to NetworkEQ.
func Network(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldEQ(FieldNetwork, v))
}

// TokenContract applies equality check predicate on the "token_contract" field. It's identical to TokenContractEQ.
func TokenContract(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldEQ(FieldTokenContract, v))
}

// AmountUsdt applies equality check predicate on the "amount_usdt" field. It's identical to AmountUsdtEQ.
func AmountUsdt(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldEQ(FieldAmountUsdt, v))
}

// Rate applies equality check predicate on the "rate" field. It's identical to RateEQ.
func Rate(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldEQ(FieldRate, v))
}

// BaseRate applies equality check predicate on the "base_rate" field. It's identical to BaseRateEQ.
func BaseRate(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldEQ(FieldBaseRate, v))
}

// PremiumPercent applies equality check predicate on the "premium_percent" field. It's identical to PremiumPercentEQ.
func PremiumPercent(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldEQ(FieldPremiumPercent, v))
}

// RateSource applies equality check predicate on the "rate_source" field. It's identical to RateSourceEQ.
func RateSource(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldEQ(FieldRateSource, v))
}

// RateQuotedAt applies equality check predicate on the "rate_quoted_at" field. It's identical to RateQuotedAtEQ.
func RateQuotedAt(v time.Time) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldEQ(FieldRateQuotedAt, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldEQ(FieldStatus, v))
}

// MatchedTxHash applies equality check predicate on the "matched_tx_hash" field. It's identical to MatchedTxHashEQ.
func MatchedTxHash(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldEQ(FieldMatchedTxHash, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldEQ(FieldExpiresAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldEQ(FieldUpdatedAt, v))
}

// OrderIDEQ applies the EQ predicate on the "order_id" field.
func OrderIDEQ(v int64) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldEQ(FieldOrderID, v))
}

// OrderIDNEQ applies the NEQ predicate on the "order_id" field.
func OrderIDNEQ(v int64) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldNEQ(FieldOrderID, v))
}

// OrderIDIn applies the In predicate on the "order_id" field.
func OrderIDIn(vs ...int64) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldIn(FieldOrderID, vs...))
}

// OrderIDNotIn applies the NotIn predicate on the "order_id" field.
func OrderIDNotIn(vs ...int64) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldNotIn(FieldOrderID, vs...))
}

// OrderIDGT applies the GT predicate on the "order_id" field.
func OrderIDGT(v int64) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldGT(FieldOrderID, v))
}

// OrderIDGTE applies the GTE predicate on the "order_id" field.
func OrderIDGTE(v int64) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldGTE(FieldOrderID, v))
}

// OrderIDLT applies the LT predicate on the "order_id" field.
func OrderIDLT(v int64) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldLT(FieldOrderID, v))
}

// OrderIDLTE applies the LTE predicate on the "order_id" field.
func OrderIDLTE(v int64) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldLTE(FieldOrderID, v))
}

// OutTradeNoEQ applies the EQ predicate on the "out_trade_no" field.
func OutTradeNoEQ(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldEQ(FieldOutTradeNo, v))
}

// OutTradeNoNEQ applies the NEQ predicate on the "out_trade_no" field.
func OutTradeNoNEQ(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldNEQ(FieldOutTradeNo, v))
}

// OutTradeNoIn applies the In predicate on the "out_trade_no" field.
func OutTradeNoIn(vs ...string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldIn(FieldOutTradeNo, vs...))
}

// OutTradeNoNotIn applies the NotIn predicate on the "out_trade_no" field.
func OutTradeNoNotIn(vs ...string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldNotIn(FieldOutTradeNo, vs...))
}

// OutTradeNoGT applies the GT predicate on the "out_trade_no" field.
func OutTradeNoGT(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldGT(FieldOutTradeNo, v))
}

// OutTradeNoGTE applies the GTE predicate on the "out_trade_no" field.
func OutTradeNoGTE(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldGTE(FieldOutTradeNo, v))
}

// OutTradeNoLT applies the LT predicate on the "out_trade_no" field.
func OutTradeNoLT(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldLT(FieldOutTradeNo, v))
}

// OutTradeNoLTE applies the LTE predicate on the "out_trade_no" field.
func OutTradeNoLTE(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldLTE(FieldOutTradeNo, v))
}

// OutTradeNoContains applies the Contains predicate on the "out_trade_no" field.
func OutTradeNoContains(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldContains(FieldOutTradeNo, v))
}

// OutTradeNoHasPrefix applies the HasPrefix predicate on the "out_trade_no" field.
func OutTradeNoHasPrefix(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldHasPrefix(FieldOutTradeNo, v))
}

// OutTradeNoHasSuffix applies the HasSuffix predicate on the "out_trade_no" field.
func OutTradeNoHasSuffix(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldHasSuffix(FieldOutTradeNo, v))
}

// OutTradeNoEqualFold applies the EqualFold predicate on the "out_trade_no" field.
func OutTradeNoEqualFold(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldEqualFold(FieldOutTradeNo, v))
}

// OutTradeNoContainsFold applies the ContainsFold predicate on the "out_trade_no" field.
func OutTradeNoContainsFold(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldContainsFold(FieldOutTradeNo, v))
}

// ProviderInstanceIDEQ applies the EQ predicate on the "provider_instance_id" field.
func ProviderInstanceIDEQ(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldEQ(FieldProviderInstanceID, v))
}

// ProviderInstanceIDNEQ applies the NEQ predicate on the "provider_instance_id" field.
func ProviderInstanceIDNEQ(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldNEQ(FieldProviderInstanceID, v))
}

// ProviderInstanceIDIn applies the In predicate on the "provider_instance_id" field.
func ProviderInstanceIDIn(vs ...string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldIn(FieldProviderInstanceID, vs...))
}

// ProviderInstanceIDNotIn applies the NotIn predicate on the "provider_instance_id" field.
func ProviderInstanceIDNotIn(vs ...string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldNotIn(FieldProviderInstanceID, vs...))
}

// ProviderInstanceIDGT applies the GT predicate on the "provider_instance_id" field.
func ProviderInstanceIDGT(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldGT(FieldProviderInstanceID, v))
}

// ProviderInstanceIDGTE applies the GTE predicate on the "provider_instance_id" field.
func ProviderInstanceIDGTE(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldGTE(FieldProviderInstanceID, v))
}

// ProviderInstanceIDLT applies the LT predicate on the "provider_instance_id" field.
func ProviderInstanceIDLT(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldLT(FieldProviderInstanceID, v))
}

// ProviderInstanceIDLTE applies the LTE predicate on the "provider_instance_id" field.
func ProviderInstanceIDLTE(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldLTE(FieldProviderInstanceID, v))
}

// ProviderInstanceIDContains applies the Contains predicate on the "provider_instance_id" field.
func ProviderInstanceIDContains(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldContains(FieldProviderInstanceID, v))
}

// ProviderInstanceIDHasPrefix applies the HasPrefix predicate on the "provider_instance_id" field.
func ProviderInstanceIDHasPrefix(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldHasPrefix(FieldProviderInstanceID, v))
}

// ProviderInstanceIDHasSuffix applies the HasSuffix predicate on the "provider_instance_id" field.
func ProviderInstanceIDHasSuffix(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldHasSuffix(FieldProviderInstanceID, v))
}

// ProviderInstanceIDEqualFold applies the EqualFold predicate on the "provider_instance_id" field.
func ProviderInstanceIDEqualFold(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldEqualFold(FieldProviderInstanceID, v))
}

// ProviderInstanceIDContainsFold applies the ContainsFold predicate on the "provider_instance_id" field.
func ProviderInstanceIDContainsFold(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldContainsFold(FieldProviderInstanceID, v))
}

// AddressEQ applies the EQ predicate on the "address" field.
func AddressEQ(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldEQ(FieldAddress, v))
}

// AddressNEQ applies the NEQ predicate on the "address" field.
func AddressNEQ(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldNEQ(FieldAddress, v))
}

// AddressIn applies the In predicate on the "address" field.
func AddressIn(vs ...string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldIn(FieldAddress, vs...))
}

// AddressNotIn applies the NotIn predicate on the "address" field.
func AddressNotIn(vs ...string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldNotIn(FieldAddress, vs...))
}

// AddressGT applies the GT predicate on the "address" field.
func AddressGT(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldGT(FieldAddress, v))
}

// AddressGTE applies the GTE predicate on the "address" field.
func AddressGTE(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldGTE(FieldAddress, v))
}

// AddressLT applies the LT predicate on the "address" field.
func AddressLT(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldLT(FieldAddress, v))
}

// AddressLTE applies the LTE predicate on the "address" field.
func AddressLTE(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldLTE(FieldAddress, v))
}

// AddressContains applies the Contains predicate on the "address" field.
func AddressContains(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldContains(FieldAddress, v))
}

// AddressHasPrefix applies the HasPrefix predicate on the "address" field.
func AddressHasPrefix(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldHasPrefix(FieldAddress, v))
}

// AddressHasSuffix applies the HasSuffix predicate on the "address" field.
func AddressHasSuffix(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldHasSuffix(FieldAddress, v))
}

// AddressEqualFold applies the EqualFold predicate on the "address" field.
func AddressEqualFold(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldEqualFold(FieldAddress, v))
}

// AddressContainsFold applies the ContainsFold predicate on the "address" field.
func AddressContainsFold(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldContainsFold(FieldAddress, v))
}

// NetworkEQ applies the EQ predicate on the "network" field.
func NetworkEQ(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldEQ(FieldNetwork, v))
}

// NetworkNEQ applies the NEQ predicate on the "network" field.
func NetworkNEQ(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldNEQ(FieldNetwork, v))
}

// NetworkIn applies the In predicate on the "network" field.
func NetworkIn(vs ...string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldIn(FieldNetwork, vs...))
}

// NetworkNotIn applies the NotIn predicate on the "network" field.
func NetworkNotIn(vs ...string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldNotIn(FieldNetwork, vs...))
}

// NetworkGT applies the GT predicate on the "network" field.
func NetworkGT(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldGT(FieldNetwork, v))
}

// NetworkGTE applies the GTE predicate on the "network" field.
func NetworkGTE(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldGTE(FieldNetwork, v))
}

// NetworkLT applies the LT predicate on the "network" field.
func NetworkLT(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldLT(FieldNetwork, v))
}

// NetworkLTE applies the LTE predicate on the "network" field.
func NetworkLTE(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldLTE(FieldNetwork, v))
}

// NetworkContains applies the Contains predicate on the "network" field.
func NetworkContains(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldContains(FieldNetwork, v))
}

// NetworkHasPrefix applies the HasPrefix predicate on the "network" field.
func NetworkHasPrefix(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldHasPrefix(FieldNetwork, v))
}

// NetworkHasSuffix applies the HasSuffix predicate on the "network" field.
func NetworkHasSuffix(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldHasSuffix(FieldNetwork, v))
}

// NetworkEqualFold applies the EqualFold predicate on the "network" field.
func NetworkEqualFold(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldEqualFold(FieldNetwork, v))
}

// NetworkContainsFold applies the ContainsFold predicate on the "network" field.
func NetworkContainsFold(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldContainsFold(FieldNetwork, v))
}

// TokenContractEQ applies the EQ predicate on the "token_contract" field.
func TokenContractEQ(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldEQ(FieldTokenContract, v))
}

// TokenContractNEQ applies the NEQ predicate on the "token_contract" field.
func TokenContractNEQ(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldNEQ(FieldTokenContract, v))
}

// TokenContractIn applies the In predicate on the "token_contract" field.
func TokenContractIn(vs ...string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldIn(FieldTokenContract, vs...))
}

// TokenContractNotIn applies the NotIn predicate on the "token_contract" field.
func TokenContractNotIn(vs ...string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldNotIn(FieldTokenContract, vs...))
}

// TokenContractGT applies the GT predicate on the "token_contract" field.
func TokenContractGT(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldGT(FieldTokenContract, v))
}

// TokenContractGTE applies the GTE predicate on the "token_contract" field.
func TokenContractGTE(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldGTE(FieldTokenContract, v))
}

// TokenContractLT applies the LT predicate on the "token_contract" field.
func TokenContractLT(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldLT(FieldTokenContract, v))
}

// TokenContractLTE applies the LTE predicate on the "token_contract" field.
func TokenContractLTE(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldLTE(FieldTokenContract, v))
}

// TokenContractContains applies the Contains predicate on the "token_contract" field.
func TokenContractContains(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldContains(FieldTokenContract, v))
}

// TokenContractHasPrefix applies the HasPrefix predicate on the "token_contract" field.
func TokenContractHasPrefix(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldHasPrefix(FieldTokenContract, v))
}

// TokenContractHasSuffix applies the HasSuffix predicate on the "token_contract" field.
func TokenContractHasSuffix(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldHasSuffix(FieldTokenContract, v))
}

// TokenContractEqualFold applies the EqualFold predicate on the "token_contract" field.
func TokenContractEqualFold(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldEqualFold(FieldTokenContract, v))
}

// TokenContractContainsFold applies the ContainsFold predicate on the "token_contract" field.
func TokenContractContainsFold(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldContainsFold(FieldTokenContract, v))
}

// AmountUsdtEQ applies the EQ predicate on the "amount_usdt" field.
func AmountUsdtEQ(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldEQ(FieldAmountUsdt, v))
}

// AmountUsdtNEQ applies the NEQ predicate on the "amount_usdt" field.
func AmountUsdtNEQ(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldNEQ(FieldAmountUsdt, v))
}

// AmountUsdtIn applies the In predicate on the "amount_usdt" field.
func AmountUsdtIn(vs ...string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldIn(FieldAmountUsdt, vs...))
}

// AmountUsdtNotIn applies the NotIn predicate on the "amount_usdt" field.
func AmountUsdtNotIn(vs ...string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldNotIn(FieldAmountUsdt, vs...))
}

// AmountUsdtGT applies the GT predicate on the "amount_usdt" field.
func AmountUsdtGT(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldGT(FieldAmountUsdt, v))
}

// AmountUsdtGTE applies the GTE predicate on the "amount_usdt" field.
func AmountUsdtGTE(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldGTE(FieldAmountUsdt, v))
}

// AmountUsdtLT applies the LT predicate on the "amount_usdt" field.
func AmountUsdtLT(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldLT(FieldAmountUsdt, v))
}

// AmountUsdtLTE applies the LTE predicate on the "amount_usdt" field.
func AmountUsdtLTE(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldLTE(FieldAmountUsdt, v))
}

// AmountUsdtContains applies the Contains predicate on the "amount_usdt" field.
func AmountUsdtContains(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldContains(FieldAmountUsdt, v))
}

// AmountUsdtHasPrefix applies the HasPrefix predicate on the "amount_usdt" field.
func AmountUsdtHasPrefix(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldHasPrefix(FieldAmountUsdt, v))
}

// AmountUsdtHasSuffix applies the HasSuffix predicate on the "amount_usdt" field.
func AmountUsdtHasSuffix(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldHasSuffix(FieldAmountUsdt, v))
}

// AmountUsdtEqualFold applies the EqualFold predicate on the "amount_usdt" field.
func AmountUsdtEqualFold(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldEqualFold(FieldAmountUsdt, v))
}

// AmountUsdtContainsFold applies the ContainsFold predicate on the "amount_usdt" field.
func AmountUsdtContainsFold(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldContainsFold(FieldAmountUsdt, v))
}

// RateEQ applies the EQ predicate on the "rate" field.
func RateEQ(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldEQ(FieldRate, v))
}

// RateNEQ applies the NEQ predicate on the "rate" field.
func RateNEQ(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldNEQ(FieldRate, v))
}

// RateIn applies the In predicate on the "rate" field.
func RateIn(vs ...string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldIn(FieldRate, vs...))
}

// RateNotIn applies the NotIn predicate on the "rate" field.
func RateNotIn(vs ...string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldNotIn(FieldRate, vs...))
}

// RateGT applies the GT predicate on the "rate" field.
func RateGT(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldGT(FieldRate, v))
}

// RateGTE applies the GTE predicate on the "rate" field.
func RateGTE(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldGTE(FieldRate, v))
}

// RateLT applies the LT predicate on the "rate" field.
func RateLT(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldLT(FieldRate, v))
}

// RateLTE applies the LTE predicate on the "rate" field.
func RateLTE(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldLTE(FieldRate, v))
}

// RateContains applies the Contains predicate on the "rate" field.
func RateContains(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldContains(FieldRate, v))
}

// RateHasPrefix applies the HasPrefix predicate on the "rate" field.
func RateHasPrefix(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldHasPrefix(FieldRate, v))
}

// RateHasSuffix applies the HasSuffix predicate on the "rate" field.
func RateHasSuffix(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldHasSuffix(FieldRate, v))
}

// RateEqualFold applies the EqualFold predicate on the "rate" field.
func RateEqualFold(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldEqualFold(FieldRate, v))
}

// RateContainsFold applies the ContainsFold predicate on the "rate" field.
func RateContainsFold(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldContainsFold(FieldRate, v))
}

// BaseRateEQ applies the EQ predicate on the "base_rate" field.
func BaseRateEQ(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldEQ(FieldBaseRate, v))
}

// BaseRateNEQ applies the NEQ predicate on the "base_rate" field.
func BaseRateNEQ(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldNEQ(FieldBaseRate, v))
}

// BaseRateIn applies the In predicate on the "base_rate" field.
func BaseRateIn(vs ...string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldIn(FieldBaseRate, vs...))
}

// BaseRateNotIn applies the NotIn predicate on the "base_rate" field.
func BaseRateNotIn(vs ...string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldNotIn(FieldBaseRate, vs...))
}

// BaseRateGT applies the GT predicate on the "base_rate" field.
func BaseRateGT(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldGT(FieldBaseRate, v))
}

// BaseRateGTE applies the GTE predicate on the "base_rate" field.
func BaseRateGTE(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldGTE(FieldBaseRate, v))
}

// BaseRateLT applies the LT predicate on the "base_rate" field.
func BaseRateLT(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldLT(FieldBaseRate, v))
}

// BaseRateLTE applies the LTE predicate on the "base_rate" field.
func BaseRateLTE(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldLTE(FieldBaseRate, v))
}

// BaseRateContains applies the Contains predicate on the "base_rate" field.
func BaseRateContains(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldContains(FieldBaseRate, v))
}

// BaseRateHasPrefix applies the HasPrefix predicate on the "base_rate" field.
func BaseRateHasPrefix(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldHasPrefix(FieldBaseRate, v))
}

// BaseRateHasSuffix applies the HasSuffix predicate on the "base_rate" field.
func BaseRateHasSuffix(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldHasSuffix(FieldBaseRate, v))
}

// BaseRateEqualFold applies the EqualFold predicate on the "base_rate" field.
func BaseRateEqualFold(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldEqualFold(FieldBaseRate, v))
}

// BaseRateContainsFold applies the ContainsFold predicate on the "base_rate" field.
func BaseRateContainsFold(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldContainsFold(FieldBaseRate, v))
}

// PremiumPercentEQ applies the EQ predicate on the "premium_percent" field.
func PremiumPercentEQ(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldEQ(FieldPremiumPercent, v))
}

// PremiumPercentNEQ applies the NEQ predicate on the "premium_percent" field.
func PremiumPercentNEQ(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldNEQ(FieldPremiumPercent, v))
}

// PremiumPercentIn applies the In predicate on the "premium_percent" field.
func PremiumPercentIn(vs ...string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldIn(FieldPremiumPercent, vs...))
}

// PremiumPercentNotIn applies the NotIn predicate on the "premium_percent" field.
func PremiumPercentNotIn(vs ...string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldNotIn(FieldPremiumPercent, vs...))
}

// PremiumPercentGT applies the GT predicate on the "premium_percent" field.
func PremiumPercentGT(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldGT(FieldPremiumPercent, v))
}

// PremiumPercentGTE applies the GTE predicate on the "premium_percent" field.
func PremiumPercentGTE(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldGTE(FieldPremiumPercent, v))
}

// PremiumPercentLT applies the LT predicate on the "premium_percent" field.
func PremiumPercentLT(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldLT(FieldPremiumPercent, v))
}

// PremiumPercentLTE applies the LTE predicate on the "premium_percent" field.
func PremiumPercentLTE(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldLTE(FieldPremiumPercent, v))
}

// PremiumPercentContains applies the Contains predicate on the "premium_percent" field.
func PremiumPercentContains(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldContains(FieldPremiumPercent, v))
}

// PremiumPercentHasPrefix applies the HasPrefix predicate on the "premium_percent" field.
func PremiumPercentHasPrefix(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldHasPrefix(FieldPremiumPercent, v))
}

// PremiumPercentHasSuffix applies the HasSuffix predicate on the "premium_percent" field.
func PremiumPercentHasSuffix(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldHasSuffix(FieldPremiumPercent, v))
}

// PremiumPercentEqualFold applies the EqualFold predicate on the "premium_percent" field.
func PremiumPercentEqualFold(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldEqualFold(FieldPremiumPercent, v))
}

// PremiumPercentContainsFold applies the ContainsFold predicate on the "premium_percent" field.
func PremiumPercentContainsFold(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldContainsFold(FieldPremiumPercent, v))
}

// RateSourceEQ applies the EQ predicate on the "rate_source" field.
func RateSourceEQ(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldEQ(FieldRateSource, v))
}

// RateSourceNEQ applies the NEQ predicate on the "rate_source" field.
func RateSourceNEQ(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldNEQ(FieldRateSource, v))
}

// RateSourceIn applies the In predicate on the "rate_source" field.
func RateSourceIn(vs ...string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldIn(FieldRateSource, vs...))
}

// RateSourceNotIn applies the NotIn predicate on the "rate_source" field.
func RateSourceNotIn(vs ...string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldNotIn(FieldRateSource, vs...))
}

// RateSourceGT applies the GT predicate on the "rate_source" field.
func RateSourceGT(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldGT(FieldRateSource, v))
}

// RateSourceGTE applies the GTE predicate on the "rate_source" field.
func RateSourceGTE(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldGTE(FieldRateSource, v))
}

// RateSourceLT applies the LT predicate on the "rate_source" field.
func RateSourceLT(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldLT(FieldRateSource, v))
}

// RateSourceLTE applies the LTE predicate on the "rate_source" field.
func RateSourceLTE(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldLTE(FieldRateSource, v))
}

// RateSourceContains applies the Contains predicate on the "rate_source" field.
func RateSourceContains(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldContains(FieldRateSource, v))
}

// RateSourceHasPrefix applies the HasPrefix predicate on the "rate_source" field.
func RateSourceHasPrefix(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldHasPrefix(FieldRateSource, v))
}

// RateSourceHasSuffix applies the HasSuffix predicate on the "rate_source" field.
func RateSourceHasSuffix(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldHasSuffix(FieldRateSource, v))
}

// RateSourceEqualFold applies the EqualFold predicate on the "rate_source" field.
func RateSourceEqualFold(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldEqualFold(FieldRateSource, v))
}

// RateSourceContainsFold applies the ContainsFold predicate on the "rate_source" field.
func RateSourceContainsFold(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldContainsFold(FieldRateSource, v))
}

// RateQuotedAtEQ applies the EQ predicate on the "rate_quoted_at" field.
func RateQuotedAtEQ(v time.Time) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldEQ(FieldRateQuotedAt, v))
}

// RateQuotedAtNEQ applies the NEQ predicate on the "rate_quoted_at" field.
func RateQuotedAtNEQ(v time.Time) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldNEQ(FieldRateQuotedAt, v))
}

// RateQuotedAtIn applies the In predicate on the "rate_quoted_at" field.
func RateQuotedAtIn(vs ...time.Time) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldIn(FieldRateQuotedAt, vs...))
}

// RateQuotedAtNotIn applies the NotIn predicate on the "rate_quoted_at" field.
func RateQuotedAtNotIn(vs ...time.Time) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldNotIn(FieldRateQuotedAt, vs...))
}

// RateQuotedAtGT applies the GT predicate on the "rate_quoted_at" field.
func RateQuotedAtGT(v time.Time) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldGT(FieldRateQuotedAt, v))
}

// RateQuotedAtGTE applies the GTE predicate on the "rate_quoted_at" field.
func RateQuotedAtGTE(v time.Time) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldGTE(FieldRateQuotedAt, v))
}

// RateQuotedAtLT applies the LT predicate on the "rate_quoted_at" field.
func RateQuotedAtLT(v time.Time) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldLT(FieldRateQuotedAt, v))
}

// RateQuotedAtLTE applies the LTE predicate on the "rate_quoted_at" field.
func RateQuotedAtLTE(v time.Time) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldLTE(FieldRateQuotedAt, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldContainsFold(FieldStatus, v))
}

// MatchedTxHashEQ applies the EQ predicate on the "matched_tx_hash" field.
func MatchedTxHashEQ(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldEQ(FieldMatchedTxHash, v))
}

// MatchedTxHashNEQ applies the NEQ predicate on the "matched_tx_hash" field.
func MatchedTxHashNEQ(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldNEQ(FieldMatchedTxHash, v))
}

// MatchedTxHashIn applies the In predicate on the "matched_tx_hash" field.
func MatchedTxHashIn(vs ...string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldIn(FieldMatchedTxHash, vs...))
}

// MatchedTxHashNotIn applies the NotIn predicate on the "matched_tx_hash" field.
func MatchedTxHashNotIn(vs ...string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldNotIn(FieldMatchedTxHash, vs...))
}

// MatchedTxHashGT applies the GT predicate on the "matched_tx_hash" field.
func MatchedTxHashGT(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldGT(FieldMatchedTxHash, v))
}

// MatchedTxHashGTE applies the GTE predicate on the "matched_tx_hash" field.
func MatchedTxHashGTE(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldGTE(FieldMatchedTxHash, v))
}

// MatchedTxHashLT applies the LT predicate on the "matched_tx_hash" field.
func MatchedTxHashLT(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldLT(FieldMatchedTxHash, v))
}

// MatchedTxHashLTE applies the LTE predicate on the "matched_tx_hash" field.
func MatchedTxHashLTE(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldLTE(FieldMatchedTxHash, v))
}

// MatchedTxHashContains applies the Contains predicate on the "matched_tx_hash" field.
func MatchedTxHashContains(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldContains(FieldMatchedTxHash, v))
}

// MatchedTxHashHasPrefix applies the HasPrefix predicate on the "matched_tx_hash" field.
func MatchedTxHashHasPrefix(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldHasPrefix(FieldMatchedTxHash, v))
}

// MatchedTxHashHasSuffix applies the HasSuffix predicate on the "matched_tx_hash" field.
func MatchedTxHashHasSuffix(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldHasSuffix(FieldMatchedTxHash, v))
}

// MatchedTxHashIsNil applies the IsNil predicate on the "matched_tx_hash" field.
func MatchedTxHashIsNil() predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldIsNull(FieldMatchedTxHash))
}

// MatchedTxHashNotNil applies the NotNil predicate on the "matched_tx_hash" field.
func MatchedTxHashNotNil() predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldNotNull(FieldMatchedTxHash))
}

// MatchedTxHashEqualFold applies the EqualFold predicate on the "matched_tx_hash" field.
func MatchedTxHashEqualFold(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldEqualFold(FieldMatchedTxHash, v))
}

// MatchedTxHashContainsFold applies the ContainsFold predicate on the "matched_tx_hash" field.
func MatchedTxHashContainsFold(v string) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldContainsFold(FieldMatchedTxHash, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldLTE(FieldExpiresAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.USDTPaymentIntent) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.USDTPaymentIntent) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.USDTPaymentIntent) predicate.USDTPaymentIntent {
	return predicate.USDTPaymentIntent(sql.NotPredicates(p))
}
