// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/usdtpaymentintent"
)

// USDTPaymentIntentUpdate is the builder for updating USDTPaymentIntent entities.
type USDTPaymentIntentUpdate struct {
	config
	hooks    []Hook
	mutation *USDTPaymentIntentMutation
}

// Where appends a list predicates to the USDTPaymentIntentUpdate builder.
func (_u *USDTPaymentIntentUpdate) Where(ps ...predicate.USDTPaymentIntent) *USDTPaymentIntentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOrderID sets the "order_id" field.
func (_u *USDTPaymentIntentUpdate) SetOrderID(v int64) *USDTPaymentIntentUpdate {
	_u.mutation.ResetOrderID()
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *USDTPaymentIntentUpdate) SetNillableOrderID(v *int64) *USDTPaymentIntentUpdate {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// AddOrderID adds value to the "order_id" field.
func (_u *USDTPaymentIntentUpdate) AddOrderID(v int64) *USDTPaymentIntentUpdate {
	_u.mutation.AddOrderID(v)
	return _u
}

// SetOutTradeNo sets the "out_trade_no" field.
func (_u *USDTPaymentIntentUpdate) SetOutTradeNo(v string) *USDTPaymentIntentUpdate {
	_u.mutation.SetOutTradeNo(v)
	return _u
}

// SetNillableOutTradeNo sets the "out_trade_no" field if the given value is not nil.
func (_u *USDTPaymentIntentUpdate) SetNillableOutTradeNo(v *string) *USDTPaymentIntentUpdate {
	if v != nil {
		_u.SetOutTradeNo(*v)
	}
	return _u
}

// SetProviderInstanceID sets the "provider_instance_id" field.
func (_u *USDTPaymentIntentUpdate) SetProviderInstanceID(v string) *USDTPaymentIntentUpdate {
	_u.mutation.SetProviderInstanceID(v)
	return _u
}

// SetNillableProviderInstanceID sets the "provider_instance_id" field if the given value is not nil.
func (_u *USDTPaymentIntentUpdate) SetNillableProviderInstanceID(v *string) *USDTPaymentIntentUpdate {
	if v != nil {
		_u.SetProviderInstanceID(*v)
	}
	return _u
}

// SetAddress sets the "address" field.
func (_u *USDTPaymentIntentUpdate) SetAddress(v string) *USDTPaymentIntentUpdate {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *USDTPaymentIntentUpdate) SetNillableAddress(v *string) *USDTPaymentIntentUpdate {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// SetNetwork sets the "network" field.
func (_u *USDTPaymentIntentUpdate) SetNetwork(v string) *USDTPaymentIntentUpdate {
	_u.mutation.SetNetwork(v)
	return _u
}

// SetNillableNetwork sets the "network" field if the given value is not nil.
func (_u *USDTPaymentIntentUpdate) SetNillableNetwork(v *string) *USDTPaymentIntentUpdate {
	if v != nil {
		_u.SetNetwork(*v)
	}
	return _u
}

// SetTokenContract sets the "token_contract" field.
func (_u *USDTPaymentIntentUpdate) SetTokenContract(v string) *USDTPaymentIntentUpdate {
	_u.mutation.SetTokenContract(v)
	return _u
}

// SetNillableTokenContract sets the "token_contract" field if the given value is not nil.
func (_u *USDTPaymentIntentUpdate) SetNillableTokenContract(v *string) *USDTPaymentIntentUpdate {
	if v != nil {
		_u.SetTokenContract(*v)
	}
	return _u
}

// SetAmountUsdt sets the "amount_usdt" field.
func (_u *USDTPaymentIntentUpdate) SetAmountUsdt(v string) *USDTPaymentIntentUpdate {
	_u.mutation.SetAmountUsdt(v)
	return _u
}

// SetNillableAmountUsdt sets the "amount_usdt" field if the given value is not nil.
func (_u *USDTPaymentIntentUpdate) SetNillableAmountUsdt(v *string) *USDTPaymentIntentUpdate {
	if v != nil {
		_u.SetAmountUsdt(*v)
	}
	return _u
}

// SetRate sets the "rate" field.
func (_u *USDTPaymentIntentUpdate) SetRate(v string) *USDTPaymentIntentUpdate {
	_u.mutation.SetRate(v)
	return _u
}

// SetNillableRate sets the "rate" field if the given value is not nil.
func (_u *USDTPaymentIntentUpdate) SetNillableRate(v *string) *USDTPaymentIntentUpdate {
	if v != nil {
		_u.SetRate(*v)
	}
	return _u
}

// SetBaseRate sets the "base_rate" field.
func (_u *USDTPaymentIntentUpdate) SetBaseRate(v string) *USDTPaymentIntentUpdate {
	_u.mutation.SetBaseRate(v)
	return _u
}

// SetNillableBaseRate sets the "base_rate" field if the given value is not nil.
func (_u *USDTPaymentIntentUpdate) SetNillableBaseRate(v *string) *USDTPaymentIntentUpdate {
	if v != nil {
		_u.SetBaseRate(*v)
	}
	return _u
}

// SetPremiumPercent sets the "premium_percent" field.
func (_u *USDTPaymentIntentUpdate) SetPremiumPercent(v string) *USDTPaymentIntentUpdate {
	_u.mutation.SetPremiumPercent(v)
	return _u
}

// SetNillablePremiumPercent sets the "premium_percent" field if the given value is not nil.
func (_u *USDTPaymentIntentUpdate) SetNillablePremiumPercent(v *string) *USDTPaymentIntentUpdate {
	if v != nil {
		_u.SetPremiumPercent(*v)
	}
	return _u
}

// SetRateSource sets the "rate_source" field.
func (_u *USDTPaymentIntentUpdate) SetRateSource(v string) *USDTPaymentIntentUpdate {
	_u.mutation.SetRateSource(v)
	return _u
}

// SetNillableRateSource sets the "rate_source" field if the given value is not nil.
func (_u *USDTPaymentIntentUpdate) SetNillableRateSource(v *string) *USDTPaymentIntentUpdate {
	if v != nil {
		_u.SetRateSource(*v)
	}
	return _u
}

// SetRateQuotedAt sets the "rate_quoted_at" field.
func (_u *USDTPaymentIntentUpdate) SetRateQuotedAt(v time.Time) *USDTPaymentIntentUpdate {
	_u.mutation.SetRateQuotedAt(v)
	return _u
}

// SetNillableRateQuotedAt sets the "rate_quoted_at" field if the given value is not nil.
func (_u *USDTPaymentIntentUpdate) SetNillableRateQuotedAt(v *time.Time) *USDTPaymentIntentUpdate {
	if v != nil {
		_u.SetRateQuotedAt(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *USDTPaymentIntentUpdate) SetStatus(v string) *USDTPaymentIntentUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *USDTPaymentIntentUpdate) SetNillableStatus(v *string) *USDTPaymentIntentUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetMatchedTxHash sets the "matched_tx_hash" field.
func (_u *USDTPaymentIntentUpdate) SetMatchedTxHash(v string) *USDTPaymentIntentUpdate {
	_u.mutation.SetMatchedTxHash(v)
	return _u
}

// SetNillableMatchedTxHash sets the "matched_tx_hash" field if the given value is not nil.
func (_u *USDTPaymentIntentUpdate) SetNillableMatchedTxHash(v *string) *USDTPaymentIntentUpdate {
	if v != nil {
		_u.SetMatchedTxHash(*v)
	}
	return _u
}

// ClearMatchedTxHash clears the value of the "matched_tx_hash" field.
func (_u *USDTPaymentIntentUpdate) ClearMatchedTxHash() *USDTPaymentIntentUpdate {
	_u.mutation.ClearMatchedTxHash()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *USDTPaymentIntentUpdate) SetExpiresAt(v time.Time) *USDTPaymentIntentUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *USDTPaymentIntentUpdate) SetNillableExpiresAt(v *time.Time) *USDTPaymentIntentUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *USDTPaymentIntentUpdate) SetUpdatedAt(v time.Time) *USDTPaymentIntentUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the USDTPaymentIntentMutation object of the builder.
func (_u *USDTPaymentIntentUpdate) Mutation() *USDTPaymentIntentMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *USDTPaymentIntentUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *USDTPaymentIntentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *USDTPaymentIntentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *USDTPaymentIntentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *USDTPaymentIntentUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := usdtpaymentintent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *USDTPaymentIntentUpdate) check() error {
	if v, ok := _u.mutation.OutTradeNo(); ok {
		if err := usdtpaymentintent.OutTradeNoValidator(v); err != nil {
			return &ValidationError{Name: "out_trade_no", err: fmt.Errorf(`ent: validator failed for field "USDTPaymentIntent.out_trade_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderInstanceID(); ok {
		if err := usdtpaymentintent.ProviderInstanceIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_instance_id", err: fmt.Errorf(`ent: validator failed for field "USDTPaymentIntent.provider_instance_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Address(); ok {
		if err := usdtpaymentintent.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "USDTPaymentIntent.address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Network(); ok {
		if err := usdtpaymentintent.NetworkValidator(v); err != nil {
			return &ValidationError{Name: "network", err: fmt.Errorf(`ent: validator failed for field "USDTPaymentIntent.network": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TokenContract(); ok {
		if err := usdtpaymentintent.TokenContractValidator(v); err != nil {
			return &ValidationError{Name: "token_contract", err: fmt.Errorf(`ent: validator failed for field "USDTPaymentIntent.token_contract": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AmountUsdt(); ok {
		if err := usdtpaymentintent.AmountUsdtValidator(v); err != nil {
			return &ValidationError{Name: "amount_usdt", err: fmt.Errorf(`ent: validator failed for field "USDTPaymentIntent.amount_usdt": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Rate(); ok {
		if err := usdtpaymentintent.RateValidator(v); err != nil {
			return &ValidationError{Name: "rate", err: fmt.Errorf(`ent: validator failed for field "USDTPaymentIntent.rate": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BaseRate(); ok {
		if err := usdtpaymentintent.BaseRateValidator(v); err != nil {
			return &ValidationError{Name: "base_rate", err: fmt.Errorf(`ent: validator failed for field "USDTPaymentIntent.base_rate": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PremiumPercent(); ok {
		if err := usdtpaymentintent.PremiumPercentValidator(v); err != nil {
			return &ValidationError{Name: "premium_percent", err: fmt.Errorf(`ent: validator failed for field "USDTPaymentIntent.premium_percent": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RateSource(); ok {
		if err := usdtpaymentintent.RateSourceValidator(v); err != nil {
			return &ValidationError{Name: "rate_source", err: fmt.Errorf(`ent: validator failed for field "USDTPaymentIntent.rate_source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := usdtpaymentintent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "USDTPaymentIntent.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MatchedTxHash(); ok {
		if err := usdtpaymentintent.MatchedTxHashValidator(v); err != nil {
			return &ValidationError{Name: "matched_tx_hash", err: fmt.Errorf(`ent: validator failed for field "USDTPaymentIntent.matched_tx_hash": %w`, err)}
		}
	}
	return nil
}

func (_u *USDTPaymentIntentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usdtpaymentintent.Table, usdtpaymentintent.Columns, sqlgraph.NewFieldSpec(usdtpaymentintent.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrderID(); ok {
		_spec.SetField(usdtpaymentintent.FieldOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOrderID(); ok {
		_spec.AddField(usdtpaymentintent.FieldOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OutTradeNo(); ok {
		_spec.SetField(usdtpaymentintent.FieldOutTradeNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderInstanceID(); ok {
		_spec.SetField(usdtpaymentintent.FieldProviderInstanceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(usdtpaymentintent.FieldAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.Network(); ok {
		_spec.SetField(usdtpaymentintent.FieldNetwork, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenContract(); ok {
		_spec.SetField(usdtpaymentintent.FieldTokenContract, field.TypeString, value)
	}
	if value, ok := _u.mutation.AmountUsdt(); ok {
		_spec.SetField(usdtpaymentintent.FieldAmountUsdt, field.TypeString, value)
	}
	if value, ok := _u.mutation.Rate(); ok {
		_spec.SetField(usdtpaymentintent.FieldRate, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaseRate(); ok {
		_spec.SetField(usdtpaymentintent.FieldBaseRate, field.TypeString, value)
	}
	if value, ok := _u.mutation.PremiumPercent(); ok {
		_spec.SetField(usdtpaymentintent.FieldPremiumPercent, field.TypeString, value)
	}
	if value, ok := _u.mutation.RateSource(); ok {
		_spec.SetField(usdtpaymentintent.FieldRateSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.RateQuotedAt(); ok {
		_spec.SetField(usdtpaymentintent.FieldRateQuotedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(usdtpaymentintent.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.MatchedTxHash(); ok {
		_spec.SetField(usdtpaymentintent.FieldMatchedTxHash, field.TypeString, value)
	}
	if _u.mutation.MatchedTxHashCleared() {
		_spec.ClearField(usdtpaymentintent.FieldMatchedTxHash, field.TypeString)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(usdtpaymentintent.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usdtpaymentintent.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usdtpaymentintent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// USDTPaymentIntentUpdateOne is the builder for updating a single USDTPaymentIntent entity.
type USDTPaymentIntentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *USDTPaymentIntentMutation
}

// SetOrderID sets the "order_id" field.
func (_u *USDTPaymentIntentUpdateOne) SetOrderID(v int64) *USDTPaymentIntentUpdateOne {
	_u.mutation.ResetOrderID()
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *USDTPaymentIntentUpdateOne) SetNillableOrderID(v *int64) *USDTPaymentIntentUpdateOne {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// AddOrderID adds value to the "order_id" field.
func (_u *USDTPaymentIntentUpdateOne) AddOrderID(v int64) *USDTPaymentIntentUpdateOne {
	_u.mutation.AddOrderID(v)
	return _u
}

// SetOutTradeNo sets the "out_trade_no" field.
func (_u *USDTPaymentIntentUpdateOne) SetOutTradeNo(v string) *USDTPaymentIntentUpdateOne {
	_u.mutation.SetOutTradeNo(v)
	return _u
}

// SetNillableOutTradeNo sets the "out_trade_no" field if the given value is not nil.
func (_u *USDTPaymentIntentUpdateOne) SetNillableOutTradeNo(v *string) *USDTPaymentIntentUpdateOne {
	if v != nil {
		_u.SetOutTradeNo(*v)
	}
	return _u
}

// SetProviderInstanceID sets the "provider_instance_id" field.
func (_u *USDTPaymentIntentUpdateOne) SetProviderInstanceID(v string) *USDTPaymentIntentUpdateOne {
	_u.mutation.SetProviderInstanceID(v)
	return _u
}

// SetNillableProviderInstanceID sets the "provider_instance_id" field if the given value is not nil.
func (_u *USDTPaymentIntentUpdateOne) SetNillableProviderInstanceID(v *string) *USDTPaymentIntentUpdateOne {
	if v != nil {
		_u.SetProviderInstanceID(*v)
	}
	return _u
}

// SetAddress sets the "address" field.
func (_u *USDTPaymentIntentUpdateOne) SetAddress(v string) *USDTPaymentIntentUpdateOne {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *USDTPaymentIntentUpdateOne) SetNillableAddress(v *string) *USDTPaymentIntentUpdateOne {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// SetNetwork sets the "network" field.
func (_u *USDTPaymentIntentUpdateOne) SetNetwork(v string) *USDTPaymentIntentUpdateOne {
	_u.mutation.SetNetwork(v)
	return _u
}

// SetNillableNetwork sets the "network" field if the given value is not nil.
func (_u *USDTPaymentIntentUpdateOne) SetNillableNetwork(v *string) *USDTPaymentIntentUpdateOne {
	if v != nil {
		_u.SetNetwork(*v)
	}
	return _u
}

// SetTokenContract sets the "token_contract" field.
func (_u *USDTPaymentIntentUpdateOne) SetTokenContract(v string) *USDTPaymentIntentUpdateOne {
	_u.mutation.SetTokenContract(v)
	return _u
}

// SetNillableTokenContract sets the "token_contract" field if the given value is not nil.
func (_u *USDTPaymentIntentUpdateOne) SetNillableTokenContract(v *string) *USDTPaymentIntentUpdateOne {
	if v != nil {
		_u.SetTokenContract(*v)
	}
	return _u
}

// SetAmountUsdt sets the "amount_usdt" field.
func (_u *USDTPaymentIntentUpdateOne) SetAmountUsdt(v string) *USDTPaymentIntentUpdateOne {
	_u.mutation.SetAmountUsdt(v)
	return _u
}

// SetNillableAmountUsdt sets the "amount_usdt" field if the given value is not nil.
func (_u *USDTPaymentIntentUpdateOne) SetNillableAmountUsdt(v *string) *USDTPaymentIntentUpdateOne {
	if v != nil {
		_u.SetAmountUsdt(*v)
	}
	return _u
}

// SetRate sets the "rate" field.
func (_u *USDTPaymentIntentUpdateOne) SetRate(v string) *USDTPaymentIntentUpdateOne {
	_u.mutation.SetRate(v)
	return _u
}

// SetNillableRate sets the "rate" field if the given value is not nil.
func (_u *USDTPaymentIntentUpdateOne) SetNillableRate(v *string) *USDTPaymentIntentUpdateOne {
	if v != nil {
		_u.SetRate(*v)
	}
	return _u
}

// SetBaseRate sets the "base_rate" field.
func (_u *USDTPaymentIntentUpdateOne) SetBaseRate(v string) *USDTPaymentIntentUpdateOne {
	_u.mutation.SetBaseRate(v)
	return _u
}

// SetNillableBaseRate sets the "base_rate" field if the given value is not nil.
func (_u *USDTPaymentIntentUpdateOne) SetNillableBaseRate(v *string) *USDTPaymentIntentUpdateOne {
	if v != nil {
		_u.SetBaseRate(*v)
	}
	return _u
}

// SetPremiumPercent sets the "premium_percent" field.
func (_u *USDTPaymentIntentUpdateOne) SetPremiumPercent(v string) *USDTPaymentIntentUpdateOne {
	_u.mutation.SetPremiumPercent(v)
	return _u
}

// SetNillablePremiumPercent sets the "premium_percent" field if the given value is not nil.
func (_u *USDTPaymentIntentUpdateOne) SetNillablePremiumPercent(v *string) *USDTPaymentIntentUpdateOne {
	if v != nil {
		_u.SetPremiumPercent(*v)
	}
	return _u
}

// SetRateSource sets the "rate_source" field.
func (_u *USDTPaymentIntentUpdateOne) SetRateSource(v string) *USDTPaymentIntentUpdateOne {
	_u.mutation.SetRateSource(v)
	return _u
}

// SetNillableRateSource sets the "rate_source" field if the given value is not nil.
func (_u *USDTPaymentIntentUpdateOne) SetNillableRateSource(v *string) *USDTPaymentIntentUpdateOne {
	if v != nil {
		_u.SetRateSource(*v)
	}
	return _u
}

// SetRateQuotedAt sets the "rate_quoted_at" field.
func (_u *USDTPaymentIntentUpdateOne) SetRateQuotedAt(v time.Time) *USDTPaymentIntentUpdateOne {
	_u.mutation.SetRateQuotedAt(v)
	return _u
}

// SetNillableRateQuotedAt sets the "rate_quoted_at" field if the given value is not nil.
func (_u *USDTPaymentIntentUpdateOne) SetNillableRateQuotedAt(v *time.Time) *USDTPaymentIntentUpdateOne {
	if v != nil {
		_u.SetRateQuotedAt(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *USDTPaymentIntentUpdateOne) SetStatus(v string) *USDTPaymentIntentUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *USDTPaymentIntentUpdateOne) SetNillableStatus(v *string) *USDTPaymentIntentUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetMatchedTxHash sets the "matched_tx_hash" field.
func (_u *USDTPaymentIntentUpdateOne) SetMatchedTxHash(v string) *USDTPaymentIntentUpdateOne {
	_u.mutation.SetMatchedTxHash(v)
	return _u
}

// SetNillableMatchedTxHash sets the "matched_tx_hash" field if the given value is not nil.
func (_u *USDTPaymentIntentUpdateOne) SetNillableMatchedTxHash(v *string) *USDTPaymentIntentUpdateOne {
	if v != nil {
		_u.SetMatchedTxHash(*v)
	}
	return _u
}

// ClearMatchedTxHash clears the value of the "matched_tx_hash" field.
func (_u *USDTPaymentIntentUpdateOne) ClearMatchedTxHash() *USDTPaymentIntentUpdateOne {
	_u.mutation.ClearMatchedTxHash()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *USDTPaymentIntentUpdateOne) SetExpiresAt(v time.Time) *USDTPaymentIntentUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *USDTPaymentIntentUpdateOne) SetNillableExpiresAt(v *time.Time) *USDTPaymentIntentUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *USDTPaymentIntentUpdateOne) SetUpdatedAt(v time.Time) *USDTPaymentIntentUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the USDTPaymentIntentMutation object of the builder.
func (_u *USDTPaymentIntentUpdateOne) Mutation() *USDTPaymentIntentMutation {
	return _u.mutation
}

// Where appends a list predicates to the USDTPaymentIntentUpdate builder.
func (_u *USDTPaymentIntentUpdateOne) Where(ps ...predicate.USDTPaymentIntent) *USDTPaymentIntentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *USDTPaymentIntentUpdateOne) Select(field string, fields ...string) *USDTPaymentIntentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated USDTPaymentIntent entity.
func (_u *USDTPaymentIntentUpdateOne) Save(ctx context.Context) (*USDTPaymentIntent, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *USDTPaymentIntentUpdateOne) SaveX(ctx context.Context) *USDTPaymentIntent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *USDTPaymentIntentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *USDTPaymentIntentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *USDTPaymentIntentUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := usdtpaymentintent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *USDTPaymentIntentUpdateOne) check() error {
	if v, ok := _u.mutation.OutTradeNo(); ok {
		if err := usdtpaymentintent.OutTradeNoValidator(v); err != nil {
			return &ValidationError{Name: "out_trade_no", err: fmt.Errorf(`ent: validator failed for field "USDTPaymentIntent.out_trade_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderInstanceID(); ok {
		if err := usdtpaymentintent.ProviderInstanceIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_instance_id", err: fmt.Errorf(`ent: validator failed for field "USDTPaymentIntent.provider_instance_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Address(); ok {
		if err := usdtpaymentintent.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "USDTPaymentIntent.address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Network(); ok {
		if err := usdtpaymentintent.NetworkValidator(v); err != nil {
			return &ValidationError{Name: "network", err: fmt.Errorf(`ent: validator failed for field "USDTPaymentIntent.network": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TokenContract(); ok {
		if err := usdtpaymentintent.TokenContractValidator(v); err != nil {
			return &ValidationError{Name: "token_contract", err: fmt.Errorf(`ent: validator failed for field "USDTPaymentIntent.token_contract": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AmountUsdt(); ok {
		if err := usdtpaymentintent.AmountUsdtValidator(v); err != nil {
			return &ValidationError{Name: "amount_usdt", err: fmt.Errorf(`ent: validator failed for field "USDTPaymentIntent.amount_usdt": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Rate(); ok {
		if err := usdtpaymentintent.RateValidator(v); err != nil {
			return &ValidationError{Name: "rate", err: fmt.Errorf(`ent: validator failed for field "USDTPaymentIntent.rate": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BaseRate(); ok {
		if err := usdtpaymentintent.BaseRateValidator(v); err != nil {
			return &ValidationError{Name: "base_rate", err: fmt.Errorf(`ent: validator failed for field "USDTPaymentIntent.base_rate": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PremiumPercent(); ok {
		if err := usdtpaymentintent.PremiumPercentValidator(v); err != nil {
			return &ValidationError{Name: "premium_percent", err: fmt.Errorf(`ent: validator failed for field "USDTPaymentIntent.premium_percent": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RateSource(); ok {
		if err := usdtpaymentintent.RateSourceValidator(v); err != nil {
			return &ValidationError{Name: "rate_source", err: fmt.Errorf(`ent: validator failed for field "USDTPaymentIntent.rate_source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := usdtpaymentintent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "USDTPaymentIntent.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MatchedTxHash(); ok {
		if err := usdtpaymentintent.MatchedTxHashValidator(v); err != nil {
			return &ValidationError{Name: "matched_tx_hash", err: fmt.Errorf(`ent: validator failed for field "USDTPaymentIntent.matched_tx_hash": %w`, err)}
		}
	}
	return nil
}

func (_u *USDTPaymentIntentUpdateOne) sqlSave(ctx context.Context) (_node *USDTPaymentIntent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usdtpaymentintent.Table, usdtpaymentintent.Columns, sqlgraph.NewFieldSpec(usdtpaymentintent.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "USDTPaymentIntent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usdtpaymentintent.FieldID)
		for _, f := range fields {
			if !usdtpaymentintent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usdtpaymentintent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrderID(); ok {
		_spec.SetField(usdtpaymentintent.FieldOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOrderID(); ok {
		_spec.AddField(usdtpaymentintent.FieldOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OutTradeNo(); ok {
		_spec.SetField(usdtpaymentintent.FieldOutTradeNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderInstanceID(); ok {
		_spec.SetField(usdtpaymentintent.FieldProviderInstanceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(usdtpaymentintent.FieldAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.Network(); ok {
		_spec.SetField(usdtpaymentintent.FieldNetwork, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenContract(); ok {
		_spec.SetField(usdtpaymentintent.FieldTokenContract, field.TypeString, value)
	}
	if value, ok := _u.mutation.AmountUsdt(); ok {
		_spec.SetField(usdtpaymentintent.FieldAmountUsdt, field.TypeString, value)
	}
	if value, ok := _u.mutation.Rate(); ok {
		_spec.SetField(usdtpaymentintent.FieldRate, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaseRate(); ok {
		_spec.SetField(usdtpaymentintent.FieldBaseRate, field.TypeString, value)
	}
	if value, ok := _u.mutation.PremiumPercent(); ok {
		_spec.SetField(usdtpaymentintent.FieldPremiumPercent, field.TypeString, value)
	}
	if value, ok := _u.mutation.RateSource(); ok {
		_spec.SetField(usdtpaymentintent.FieldRateSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.RateQuotedAt(); ok {
		_spec.SetField(usdtpaymentintent.FieldRateQuotedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(usdtpaymentintent.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.MatchedTxHash(); ok {
		_spec.SetField(usdtpaymentintent.FieldMatchedTxHash, field.TypeString, value)
	}
	if _u.mutation.MatchedTxHashCleared() {
		_spec.ClearField(usdtpaymentintent.FieldMatchedTxHash, field.TypeString)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(usdtpaymentintent.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usdtpaymentintent.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &USDTPaymentIntent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usdtpaymentintent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
