// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/usdtdeposit"
)

// USDTDepositUpdate is the builder for updating USDTDeposit entities.
type USDTDepositUpdate struct {
	config
	hooks    []Hook
	mutation *USDTDepositMutation
}

// Where appends a list predicates to the USDTDepositUpdate builder.
func (_u *USDTDepositUpdate) Where(ps ...predicate.USDTDeposit) *USDTDepositUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTxHash sets the "tx_hash" field.
func (_u *USDTDepositUpdate) SetTxHash(v string) *USDTDepositUpdate {
	_u.mutation.SetTxHash(v)
	return _u
}

// SetNillableTxHash sets the "tx_hash" field if the given value is not nil.
func (_u *USDTDepositUpdate) SetNillableTxHash(v *string) *USDTDepositUpdate {
	if v != nil {
		_u.SetTxHash(*v)
	}
	return _u
}

// SetAddress sets the "address" field.
func (_u *USDTDepositUpdate) SetAddress(v string) *USDTDepositUpdate {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *USDTDepositUpdate) SetNillableAddress(v *string) *USDTDepositUpdate {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// SetFromAddress sets the "from_address" field.
func (_u *USDTDepositUpdate) SetFromAddress(v string) *USDTDepositUpdate {
	_u.mutation.SetFromAddress(v)
	return _u
}

// SetNillableFromAddress sets the "from_address" field if the given value is not nil.
func (_u *USDTDepositUpdate) SetNillableFromAddress(v *string) *USDTDepositUpdate {
	if v != nil {
		_u.SetFromAddress(*v)
	}
	return _u
}

// SetTokenContract sets the "token_contract" field.
func (_u *USDTDepositUpdate) SetTokenContract(v string) *USDTDepositUpdate {
	_u.mutation.SetTokenContract(v)
	return _u
}

// SetNillableTokenContract sets the "token_contract" field if the given value is not nil.
func (_u *USDTDepositUpdate) SetNillableTokenContract(v *string) *USDTDepositUpdate {
	if v != nil {
		_u.SetTokenContract(*v)
	}
	return _u
}

// SetAmountUsdt sets the "amount_usdt" field.
func (_u *USDTDepositUpdate) SetAmountUsdt(v string) *USDTDepositUpdate {
	_u.mutation.SetAmountUsdt(v)
	return _u
}

// SetNillableAmountUsdt sets the "amount_usdt" field if the given value is not nil.
func (_u *USDTDepositUpdate) SetNillableAmountUsdt(v *string) *USDTDepositUpdate {
	if v != nil {
		_u.SetAmountUsdt(*v)
	}
	return _u
}

// SetBlockTimestamp sets the "block_timestamp" field.
func (_u *USDTDepositUpdate) SetBlockTimestamp(v time.Time) *USDTDepositUpdate {
	_u.mutation.SetBlockTimestamp(v)
	return _u
}

// SetNillableBlockTimestamp sets the "block_timestamp" field if the given value is not nil.
func (_u *USDTDepositUpdate) SetNillableBlockTimestamp(v *time.Time) *USDTDepositUpdate {
	if v != nil {
		_u.SetBlockTimestamp(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *USDTDepositUpdate) SetStatus(v string) *USDTDepositUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *USDTDepositUpdate) SetNillableStatus(v *string) *USDTDepositUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetMatchedOrderID sets the "matched_order_id" field.
func (_u *USDTDepositUpdate) SetMatchedOrderID(v int64) *USDTDepositUpdate {
	_u.mutation.ResetMatchedOrderID()
	_u.mutation.SetMatchedOrderID(v)
	return _u
}

// SetNillableMatchedOrderID sets the "matched_order_id" field if the given value is not nil.
func (_u *USDTDepositUpdate) SetNillableMatchedOrderID(v *int64) *USDTDepositUpdate {
	if v != nil {
		_u.SetMatchedOrderID(*v)
	}
	return _u
}

// AddMatchedOrderID adds value to the "matched_order_id" field.
func (_u *USDTDepositUpdate) AddMatchedOrderID(v int64) *USDTDepositUpdate {
	_u.mutation.AddMatchedOrderID(v)
	return _u
}

// ClearMatchedOrderID clears the value of the "matched_order_id" field.
func (_u *USDTDepositUpdate) ClearMatchedOrderID() *USDTDepositUpdate {
	_u.mutation.ClearMatchedOrderID()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *USDTDepositUpdate) SetNotes(v string) *USDTDepositUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *USDTDepositUpdate) SetNillableNotes(v *string) *USDTDepositUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *USDTDepositUpdate) ClearNotes() *USDTDepositUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *USDTDepositUpdate) SetUpdatedAt(v time.Time) *USDTDepositUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the USDTDepositMutation object of the builder.
func (_u *USDTDepositUpdate) Mutation() *USDTDepositMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *USDTDepositUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *USDTDepositUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *USDTDepositUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *USDTDepositUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *USDTDepositUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := usdtdeposit.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *USDTDepositUpdate) check() error {
	if v, ok := _u.mutation.TxHash(); ok {
		if err := usdtdeposit.TxHashValidator(v); err != nil {
			return &ValidationError{Name: "tx_hash", err: fmt.Errorf(`ent: validator failed for field "USDTDeposit.tx_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Address(); ok {
		if err := usdtdeposit.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "USDTDeposit.address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FromAddress(); ok {
		if err := usdtdeposit.FromAddressValidator(v); err != nil {
			return &ValidationError{Name: "from_address", err: fmt.Errorf(`ent: validator failed for field "USDTDeposit.from_address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TokenContract(); ok {
		if err := usdtdeposit.TokenContractValidator(v); err != nil {
			return &ValidationError{Name: "token_contract", err: fmt.Errorf(`ent: validator failed for field "USDTDeposit.token_contract": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AmountUsdt(); ok {
		if err := usdtdeposit.AmountUsdtValidator(v); err != nil {
			return &ValidationError{Name: "amount_usdt", err: fmt.Errorf(`ent: validator failed for field "USDTDeposit.amount_usdt": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := usdtdeposit.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "USDTDeposit.status": %w`, err)}
		}
	}
	return nil
}

func (_u *USDTDepositUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usdtdeposit.Table, usdtdeposit.Columns, sqlgraph.NewFieldSpec(usdtdeposit.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TxHash(); ok {
		_spec.SetField(usdtdeposit.FieldTxHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(usdtdeposit.FieldAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.FromAddress(); ok {
		_spec.SetField(usdtdeposit.FieldFromAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenContract(); ok {
		_spec.SetField(usdtdeposit.FieldTokenContract, field.TypeString, value)
	}
	if value, ok := _u.mutation.AmountUsdt(); ok {
		_spec.SetField(usdtdeposit.FieldAmountUsdt, field.TypeString, value)
	}
	if value, ok := _u.mutation.BlockTimestamp(); ok {
		_spec.SetField(usdtdeposit.FieldBlockTimestamp, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(usdtdeposit.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.MatchedOrderID(); ok {
		_spec.SetField(usdtdeposit.FieldMatchedOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMatchedOrderID(); ok {
		_spec.AddField(usdtdeposit.FieldMatchedOrderID, field.TypeInt64, value)
	}
	if _u.mutation.MatchedOrderIDCleared() {
		_spec.ClearField(usdtdeposit.FieldMatchedOrderID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(usdtdeposit.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(usdtdeposit.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usdtdeposit.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usdtdeposit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// USDTDepositUpdateOne is the builder for updating a single USDTDeposit entity.
type USDTDepositUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *USDTDepositMutation
}

// SetTxHash sets the "tx_hash" field.
func (_u *USDTDepositUpdateOne) SetTxHash(v string) *USDTDepositUpdateOne {
	_u.mutation.SetTxHash(v)
	return _u
}

// SetNillableTxHash sets the "tx_hash" field if the given value is not nil.
func (_u *USDTDepositUpdateOne) SetNillableTxHash(v *string) *USDTDepositUpdateOne {
	if v != nil {
		_u.SetTxHash(*v)
	}
	return _u
}

// SetAddress sets the "address" field.
func (_u *USDTDepositUpdateOne) SetAddress(v string) *USDTDepositUpdateOne {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *USDTDepositUpdateOne) SetNillableAddress(v *string) *USDTDepositUpdateOne {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// SetFromAddress sets the "from_address" field.
func (_u *USDTDepositUpdateOne) SetFromAddress(v string) *USDTDepositUpdateOne {
	_u.mutation.SetFromAddress(v)
	return _u
}

// SetNillableFromAddress sets the "from_address" field if the given value is not nil.
func (_u *USDTDepositUpdateOne) SetNillableFromAddress(v *string) *USDTDepositUpdateOne {
	if v != nil {
		_u.SetFromAddress(*v)
	}
	return _u
}

// SetTokenContract sets the "token_contract" field.
func (_u *USDTDepositUpdateOne) SetTokenContract(v string) *USDTDepositUpdateOne {
	_u.mutation.SetTokenContract(v)
	return _u
}

// SetNillableTokenContract sets the "token_contract" field if the given value is not nil.
func (_u *USDTDepositUpdateOne) SetNillableTokenContract(v *string) *USDTDepositUpdateOne {
	if v != nil {
		_u.SetTokenContract(*v)
	}
	return _u
}

// SetAmountUsdt sets the "amount_usdt" field.
func (_u *USDTDepositUpdateOne) SetAmountUsdt(v string) *USDTDepositUpdateOne {
	_u.mutation.SetAmountUsdt(v)
	return _u
}

// SetNillableAmountUsdt sets the "amount_usdt" field if the given value is not nil.
func (_u *USDTDepositUpdateOne) SetNillableAmountUsdt(v *string) *USDTDepositUpdateOne {
	if v != nil {
		_u.SetAmountUsdt(*v)
	}
	return _u
}

// SetBlockTimestamp sets the "block_timestamp" field.
func (_u *USDTDepositUpdateOne) SetBlockTimestamp(v time.Time) *USDTDepositUpdateOne {
	_u.mutation.SetBlockTimestamp(v)
	return _u
}

// SetNillableBlockTimestamp sets the "block_timestamp" field if the given value is not nil.
func (_u *USDTDepositUpdateOne) SetNillableBlockTimestamp(v *time.Time) *USDTDepositUpdateOne {
	if v != nil {
		_u.SetBlockTimestamp(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *USDTDepositUpdateOne) SetStatus(v string) *USDTDepositUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *USDTDepositUpdateOne) SetNillableStatus(v *string) *USDTDepositUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetMatchedOrderID sets the "matched_order_id" field.
func (_u *USDTDepositUpdateOne) SetMatchedOrderID(v int64) *USDTDepositUpdateOne {
	_u.mutation.ResetMatchedOrderID()
	_u.mutation.SetMatchedOrderID(v)
	return _u
}

// SetNillableMatchedOrderID sets the "matched_order_id" field if the given value is not nil.
func (_u *USDTDepositUpdateOne) SetNillableMatchedOrderID(v *int64) *USDTDepositUpdateOne {
	if v != nil {
		_u.SetMatchedOrderID(*v)
	}
	return _u
}

// AddMatchedOrderID adds value to the "matched_order_id" field.
func (_u *USDTDepositUpdateOne) AddMatchedOrderID(v int64) *USDTDepositUpdateOne {
	_u.mutation.AddMatchedOrderID(v)
	return _u
}

// ClearMatchedOrderID clears the value of the "matched_order_id" field.
func (_u *USDTDepositUpdateOne) ClearMatchedOrderID() *USDTDepositUpdateOne {
	_u.mutation.ClearMatchedOrderID()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *USDTDepositUpdateOne) SetNotes(v string) *USDTDepositUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *USDTDepositUpdateOne) SetNillableNotes(v *string) *USDTDepositUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *USDTDepositUpdateOne) ClearNotes() *USDTDepositUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *USDTDepositUpdateOne) SetUpdatedAt(v time.Time) *USDTDepositUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the USDTDepositMutation object of the builder.
func (_u *USDTDepositUpdateOne) Mutation() *USDTDepositMutation {
	return _u.mutation
}

// Where appends a list predicates to the USDTDepositUpdate builder.
func (_u *USDTDepositUpdateOne) Where(ps ...predicate.USDTDeposit) *USDTDepositUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *USDTDepositUpdateOne) Select(field string, fields ...string) *USDTDepositUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated USDTDeposit entity.
func (_u *USDTDepositUpdateOne) Save(ctx context.Context) (*USDTDeposit, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *USDTDepositUpdateOne) SaveX(ctx context.Context) *USDTDeposit {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *USDTDepositUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *USDTDepositUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *USDTDepositUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := usdtdeposit.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *USDTDepositUpdateOne) check() error {
	if v, ok := _u.mutation.TxHash(); ok {
		if err := usdtdeposit.TxHashValidator(v); err != nil {
			return &ValidationError{Name: "tx_hash", err: fmt.Errorf(`ent: validator failed for field "USDTDeposit.tx_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Address(); ok {
		if err := usdtdeposit.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "USDTDeposit.address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FromAddress(); ok {
		if err := usdtdeposit.FromAddressValidator(v); err != nil {
			return &ValidationError{Name: "from_address", err: fmt.Errorf(`ent: validator failed for field "USDTDeposit.from_address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TokenContract(); ok {
		if err := usdtdeposit.TokenContractValidator(v); err != nil {
			return &ValidationError{Name: "token_contract", err: fmt.Errorf(`ent: validator failed for field "USDTDeposit.token_contract": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AmountUsdt(); ok {
		if err := usdtdeposit.AmountUsdtValidator(v); err != nil {
			return &ValidationError{Name: "amount_usdt", err: fmt.Errorf(`ent: validator failed for field "USDTDeposit.amount_usdt": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := usdtdeposit.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "USDTDeposit.status": %w`, err)}
		}
	}
	return nil
}

func (_u *USDTDepositUpdateOne) sqlSave(ctx context.Context) (_node *USDTDeposit, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usdtdeposit.Table, usdtdeposit.Columns, sqlgraph.NewFieldSpec(usdtdeposit.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "USDTDeposit.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usdtdeposit.FieldID)
		for _, f := range fields {
			if !usdtdeposit.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usdtdeposit.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TxHash(); ok {
		_spec.SetField(usdtdeposit.FieldTxHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(usdtdeposit.FieldAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.FromAddress(); ok {
		_spec.SetField(usdtdeposit.FieldFromAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenContract(); ok {
		_spec.SetField(usdtdeposit.FieldTokenContract, field.TypeString, value)
	}
	if value, ok := _u.mutation.AmountUsdt(); ok {
		_spec.SetField(usdtdeposit.FieldAmountUsdt, field.TypeString, value)
	}
	if value, ok := _u.mutation.BlockTimestamp(); ok {
		_spec.SetField(usdtdeposit.FieldBlockTimestamp, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(usdtdeposit.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.MatchedOrderID(); ok {
		_spec.SetField(usdtdeposit.FieldMatchedOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMatchedOrderID(); ok {
		_spec.AddField(usdtdeposit.FieldMatchedOrderID, field.TypeInt64, value)
	}
	if _u.mutation.MatchedOrderIDCleared() {
		_spec.ClearField(usdtdeposit.FieldMatchedOrderID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(usdtdeposit.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(usdtdeposit.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usdtdeposit.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &USDTDeposit{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usdtdeposit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
