// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/usdtpaymentintent"
)

// USDTPaymentIntentCreate is the builder for creating a USDTPaymentIntent entity.
type USDTPaymentIntentCreate struct {
	config
	mutation *USDTPaymentIntentMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetOrderID sets the "order_id" field.
func (_c *USDTPaymentIntentCreate) SetOrderID(v int64) *USDTPaymentIntentCreate {
	_c.mutation.SetOrderID(v)
	return _c
}

// SetOutTradeNo sets the "out_trade_no" field.
func (_c *USDTPaymentIntentCreate) SetOutTradeNo(v string) *USDTPaymentIntentCreate {
	_c.mutation.SetOutTradeNo(v)
	return _c
}

// SetProviderInstanceID sets the "provider_instance_id" field.
func (_c *USDTPaymentIntentCreate) SetProviderInstanceID(v string) *USDTPaymentIntentCreate {
	_c.mutation.SetProviderInstanceID(v)
	return _c
}

// SetAddress sets the "address" field.
func (_c *USDTPaymentIntentCreate) SetAddress(v string) *USDTPaymentIntentCreate {
	_c.mutation.SetAddress(v)
	return _c
}

// SetNetwork sets the "network" field.
func (_c *USDTPaymentIntentCreate) SetNetwork(v string) *USDTPaymentIntentCreate {
	_c.mutation.SetNetwork(v)
	return _c
}

// SetNillableNetwork sets the "network" field if the given value is not nil.
func (_c *USDTPaymentIntentCreate) SetNillableNetwork(v *string) *USDTPaymentIntentCreate {
	if v != nil {
		_c.SetNetwork(*v)
	}
	return _c
}

// SetTokenContract sets the "token_contract" field.
func (_c *USDTPaymentIntentCreate) SetTokenContract(v string) *USDTPaymentIntentCreate {
	_c.mutation.SetTokenContract(v)
	return _c
}

// SetAmountUsdt sets the "amount_usdt" field.
func (_c *USDTPaymentIntentCreate) SetAmountUsdt(v string) *USDTPaymentIntentCreate {
	_c.mutation.SetAmountUsdt(v)
	return _c
}

// SetRate sets the "rate" field.
func (_c *USDTPaymentIntentCreate) SetRate(v string) *USDTPaymentIntentCreate {
	_c.mutation.SetRate(v)
	return _c
}

// SetBaseRate sets the "base_rate" field.
func (_c *USDTPaymentIntentCreate) SetBaseRate(v string) *USDTPaymentIntentCreate {
	_c.mutation.SetBaseRate(v)
	return _c
}

// SetPremiumPercent sets the "premium_percent" field.
func (_c *USDTPaymentIntentCreate) SetPremiumPercent(v string) *USDTPaymentIntentCreate {
	_c.mutation.SetPremiumPercent(v)
	return _c
}

// SetRateSource sets the "rate_source" field.
func (_c *USDTPaymentIntentCreate) SetRateSource(v string) *USDTPaymentIntentCreate {
	_c.mutation.SetRateSource(v)
	return _c
}

// SetRateQuotedAt sets the "rate_quoted_at" field.
func (_c *USDTPaymentIntentCreate) SetRateQuotedAt(v time.Time) *USDTPaymentIntentCreate {
	_c.mutation.SetRateQuotedAt(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *USDTPaymentIntentCreate) SetStatus(v string) *USDTPaymentIntentCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *USDTPaymentIntentCreate) SetNillableStatus(v *string) *USDTPaymentIntentCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetMatchedTxHash sets the "matched_tx_hash" field.
func (_c *USDTPaymentIntentCreate) SetMatchedTxHash(v string) *USDTPaymentIntentCreate {
	_c.mutation.SetMatchedTxHash(v)
	return _c
}

// SetNillableMatchedTxHash sets the "matched_tx_hash" field if the given value is not nil.
func (_c *USDTPaymentIntentCreate) SetNillableMatchedTxHash(v *string) *USDTPaymentIntentCreate {
	if v != nil {
		_c.SetMatchedTxHash(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *USDTPaymentIntentCreate) SetExpiresAt(v time.Time) *USDTPaymentIntentCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *USDTPaymentIntentCreate) SetCreatedAt(v time.Time) *USDTPaymentIntentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *USDTPaymentIntentCreate) SetNillableCreatedAt(v *time.Time) *USDTPaymentIntentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *USDTPaymentIntentCreate) SetUpdatedAt(v time.Time) *USDTPaymentIntentCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *USDTPaymentIntentCreate) SetNillableUpdatedAt(v *time.Time) *USDTPaymentIntentCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the USDTPaymentIntentMutation object of the builder.
func (_c *USDTPaymentIntentCreate) Mutation() *USDTPaymentIntentMutation {
	return _c.mutation
}

// Save creates the USDTPaymentIntent in the database.
func (_c *USDTPaymentIntentCreate) Save(ctx context.Context) (*USDTPaymentIntent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *USDTPaymentIntentCreate) SaveX(ctx context.Context) *USDTPaymentIntent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *USDTPaymentIntentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *USDTPaymentIntentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *USDTPaymentIntentCreate) defaults() {
	if _, ok := _c.mutation.Network(); !ok {
		v := usdtpaymentintent.DefaultNetwork
		_c.mutation.SetNetwork(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := usdtpaymentintent.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := usdtpaymentintent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := usdtpaymentintent.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *USDTPaymentIntentCreate) check() error {
	if _, ok := _c.mutation.OrderID(); !ok {
		return &ValidationError{Name: "order_id", err: errors.New(`ent: missing required field "USDTPaymentIntent.order_id"`)}
	}
	if _, ok := _c.mutation.OutTradeNo(); !ok {
		return &ValidationError{Name: "out_trade_no", err: errors.New(`ent: missing required field "USDTPaymentIntent.out_trade_no"`)}
	}
	if v, ok := _c.mutation.OutTradeNo(); ok {
		if err := usdtpaymentintent.OutTradeNoValidator(v); err != nil {
			return &ValidationError{Name: "out_trade_no", err: fmt.Errorf(`ent: validator failed for field "USDTPaymentIntent.out_trade_no": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProviderInstanceID(); !ok {
		return &ValidationError{Name: "provider_instance_id", err: errors.New(`ent: missing required field "USDTPaymentIntent.provider_instance_id"`)}
	}
	if v, ok := _c.mutation.ProviderInstanceID(); ok {
		if err := usdtpaymentintent.ProviderInstanceIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_instance_id", err: fmt.Errorf(`ent: validator failed for field "USDTPaymentIntent.provider_instance_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Address(); !ok {
		return &ValidationError{Name: "address", err: errors.New(`ent: missing required field "USDTPaymentIntent.address"`)}
	}
	if v, ok := _c.mutation.Address(); ok {
		if err := usdtpaymentintent.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "USDTPaymentIntent.address": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Network(); !ok {
		return &ValidationError{Name: "network", err: errors.New(`ent: missing required field "USDTPaymentIntent.network"`)}
	}
	if v, ok := _c.mutation.Network(); ok {
		if err := usdtpaymentintent.NetworkValidator(v); err != nil {
			return &ValidationError{Name: "network", err: fmt.Errorf(`ent: validator failed for field "USDTPaymentIntent.network": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TokenContract(); !ok {
		return &ValidationError{Name: "token_contract", err: errors.New(`ent: missing required field "USDTPaymentIntent.token_contract"`)}
	}
	if v, ok := _c.mutation.TokenContract(); ok {
		if err := usdtpaymentintent.TokenContractValidator(v); err != nil {
			return &ValidationError{Name: "token_contract", err: fmt.Errorf(`ent: validator failed for field "USDTPaymentIntent.token_contract": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AmountUsdt(); !ok {
		return &ValidationError{Name: "amount_usdt", err: errors.New(`ent: missing required field "USDTPaymentIntent.amount_usdt"`)}
	}
	if v, ok := _c.mutation.AmountUsdt(); ok {
		if err := usdtpaymentintent.AmountUsdtValidator(v); err != nil {
			return &ValidationError{Name: "amount_usdt", err: fmt.Errorf(`ent: validator failed for field "USDTPaymentIntent.amount_usdt": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Rate(); !ok {
		return &ValidationError{Name: "rate", err: errors.New(`ent: missing required field "USDTPaymentIntent.rate"`)}
	}
	if v, ok := _c.mutation.Rate(); ok {
		if err := usdtpaymentintent.RateValidator(v); err != nil {
			return &ValidationError{Name: "rate", err: fmt.Errorf(`ent: validator failed for field "USDTPaymentIntent.rate": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BaseRate(); !ok {
		return &ValidationError{Name: "base_rate", err: errors.New(`ent: missing required field "USDTPaymentIntent.base_rate"`)}
	}
	if v, ok := _c.mutation.BaseRate(); ok {
		if err := usdtpaymentintent.BaseRateValidator(v); err != nil {
			return &ValidationError{Name: "base_rate", err: fmt.Errorf(`ent: validator failed for field "USDTPaymentIntent.base_rate": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PremiumPercent(); !ok {
		return &ValidationError{Name: "premium_percent", err: errors.New(`ent: missing required field "USDTPaymentIntent.premium_percent"`)}
	}
	if v, ok := _c.mutation.PremiumPercent(); ok {
		if err := usdtpaymentintent.PremiumPercentValidator(v); err != nil {
			return &ValidationError{Name: "premium_percent", err: fmt.Errorf(`ent: validator failed for field "USDTPaymentIntent.premium_percent": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RateSource(); !ok {
		return &ValidationError{Name: "rate_source", err: errors.New(`ent: missing required field "USDTPaymentIntent.rate_source"`)}
	}
	if v, ok := _c.mutation.RateSource(); ok {
		if err := usdtpaymentintent.RateSourceValidator(v); err != nil {
			return &ValidationError{Name: "rate_source", err: fmt.Errorf(`ent: validator failed for field "USDTPaymentIntent.rate_source": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RateQuotedAt(); !ok {
		return &ValidationError{Name: "rate_quoted_at", err: errors.New(`ent: missing required field "USDTPaymentIntent.rate_quoted_at"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "USDTPaymentIntent.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := usdtpaymentintent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "USDTPaymentIntent.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.MatchedTxHash(); ok {
		if err := usdtpaymentintent.MatchedTxHashValidator(v); err != nil {
			return &ValidationError{Name: "matched_tx_hash", err: fmt.Errorf(`ent: validator failed for field "USDTPaymentIntent.matched_tx_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "USDTPaymentIntent.expires_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "USDTPaymentIntent.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "USDTPaymentIntent.updated_at"`)}
	}
	return nil
}

func (_c *USDTPaymentIntentCreate) sqlSave(ctx context.Context) (*USDTPaymentIntent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *USDTPaymentIntentCreate) createSpec() (*USDTPaymentIntent, *sqlgraph.CreateSpec) {
	var (
		_node = &USDTPaymentIntent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(usdtpaymentintent.Table, sqlgraph.NewFieldSpec(usdtpaymentintent.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.OrderID(); ok {
		_spec.SetField(usdtpaymentintent.FieldOrderID, field.TypeInt64, value)
		_node.OrderID = value
	}
	if value, ok := _c.mutation.OutTradeNo(); ok {
		_spec.SetField(usdtpaymentintent.FieldOutTradeNo, field.TypeString, value)
		_node.OutTradeNo = value
	}
	if value, ok := _c.mutation.ProviderInstanceID(); ok {
		_spec.SetField(usdtpaymentintent.FieldProviderInstanceID, field.TypeString, value)
		_node.ProviderInstanceID = value
	}
	if value, ok := _c.mutation.Address(); ok {
		_spec.SetField(usdtpaymentintent.FieldAddress, field.TypeString, value)
		_node.Address = value
	}
	if value, ok := _c.mutation.Network(); ok {
		_spec.SetField(usdtpaymentintent.FieldNetwork, field.TypeString, value)
		_node.Network = value
	}
	if value, ok := _c.mutation.TokenContract(); ok {
		_spec.SetField(usdtpaymentintent.FieldTokenContract, field.TypeString, value)
		_node.TokenContract = value
	}
	if value, ok := _c.mutation.AmountUsdt(); ok {
		_spec.SetField(usdtpaymentintent.FieldAmountUsdt, field.TypeString, value)
		_node.AmountUsdt = value
	}
	if value, ok := _c.mutation.Rate(); ok {
		_spec.SetField(usdtpaymentintent.FieldRate, field.TypeString, value)
		_node.Rate = value
	}
	if value, ok := _c.mutation.BaseRate(); ok {
		_spec.SetField(usdtpaymentintent.FieldBaseRate, field.TypeString, value)
		_node.BaseRate = value
	}
	if value, ok := _c.mutation.PremiumPercent(); ok {
		_spec.SetField(usdtpaymentintent.FieldPremiumPercent, field.TypeString, value)
		_node.PremiumPercent = value
	}
	if value, ok := _c.mutation.RateSource(); ok {
		_spec.SetField(usdtpaymentintent.FieldRateSource, field.TypeString, value)
		_node.RateSource = value
	}
	if value, ok := _c.mutation.RateQuotedAt(); ok {
		_spec.SetField(usdtpaymentintent.FieldRateQuotedAt, field.TypeTime, value)
		_node.RateQuotedAt = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(usdtpaymentintent.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.MatchedTxHash(); ok {
		_spec.SetField(usdtpaymentintent.FieldMatchedTxHash, field.TypeString, value)
		_node.MatchedTxHash = &value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(usdtpaymentintent.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(usdtpaymentintent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(usdtpaymentintent.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.USDTPaymentIntent.Create().
//		SetOrderID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.USDTPaymentIntentUpsert) {
//			SetOrderID(v+v).
//		}).
//		Exec(ctx)
func (_c *USDTPaymentIntentCreate) OnConflict(opts ...sql.ConflictOption) *USDTPaymentIntentUpsertOne {
	_c.conflict = opts
	return &USDTPaymentIntentUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.USDTPaymentIntent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *USDTPaymentIntentCreate) OnConflictColumns(columns ...string) *USDTPaymentIntentUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &USDTPaymentIntentUpsertOne{
		create: _c,
	}
}

type (
	// USDTPaymentIntentUpsertOne is the builder for "upsert"-ing
	//  one USDTPaymentIntent node.
	USDTPaymentIntentUpsertOne struct {
		create *USDTPaymentIntentCreate
	}

	// USDTPaymentIntentUpsert is the "OnConflict" setter.
	USDTPaymentIntentUpsert struct {
		*sql.UpdateSet
	}
)

// SetOrderID sets the "order_id" field.
func (u *USDTPaymentIntentUpsert) SetOrderID(v int64) *USDTPaymentIntentUpsert {
	u.Set(usdtpaymentintent.FieldOrderID, v)
	return u
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *USDTPaymentIntentUpsert) UpdateOrderID() *USDTPaymentIntentUpsert {
	u.SetExcluded(usdtpaymentintent.FieldOrderID)
	return u
}

// AddOrderID adds v to the "order_id" field.
func (u *USDTPaymentIntentUpsert) AddOrderID(v int64) *USDTPaymentIntentUpsert {
	u.Add(usdtpaymentintent.FieldOrderID, v)
	return u
}

// SetOutTradeNo sets the "out_trade_no" field.
func (u *USDTPaymentIntentUpsert) SetOutTradeNo(v string) *USDTPaymentIntentUpsert {
	u.Set(usdtpaymentintent.FieldOutTradeNo, v)
	return u
}

// UpdateOutTradeNo sets the "out_trade_no" field to the value that was provided on create.
func (u *USDTPaymentIntentUpsert) UpdateOutTradeNo() *USDTPaymentIntentUpsert {
	u.SetExcluded(usdtpaymentintent.FieldOutTradeNo)
	return u
}

// SetProviderInstanceID sets the "provider_instance_id" field.
func (u *USDTPaymentIntentUpsert) SetProviderInstanceID(v string) *USDTPaymentIntentUpsert {
	u.Set(usdtpaymentintent.FieldProviderInstanceID, v)
	return u
}

// UpdateProviderInstanceID sets the "provider_instance_id" field to the value that was provided on create.
func (u *USDTPaymentIntentUpsert) UpdateProviderInstanceID() *USDTPaymentIntentUpsert {
	u.SetExcluded(usdtpaymentintent.FieldProviderInstanceID)
	return u
}

// SetAddress sets the "address" field.
func (u *USDTPaymentIntentUpsert) SetAddress(v string) *USDTPaymentIntentUpsert {
	u.Set(usdtpaymentintent.FieldAddress, v)
	return u
}

// UpdateAddress sets the "address" field to the value that was provided on create.
func (u *USDTPaymentIntentUpsert) UpdateAddress() *USDTPaymentIntentUpsert {
	u.SetExcluded(usdtpaymentintent.FieldAddress)
	return u
}

// SetNetwork sets the "network" field.
func (u *USDTPaymentIntentUpsert) SetNetwork(v string) *USDTPaymentIntentUpsert {
	u.Set(usdtpaymentintent.FieldNetwork, v)
	return u
}

// UpdateNetwork sets the "network" field to the value that was provided on create.
func (u *USDTPaymentIntentUpsert) UpdateNetwork() *USDTPaymentIntentUpsert {
	u.SetExcluded(usdtpaymentintent.FieldNetwork)
	return u
}

// SetTokenContract sets the "token_contract" field.
func (u *USDTPaymentIntentUpsert) SetTokenContract(v string) *USDTPaymentIntentUpsert {
	u.Set(usdtpaymentintent.FieldTokenContract, v)
	return u
}

// UpdateTokenContract sets the "token_contract" field to the value that was provided on create.
func (u *USDTPaymentIntentUpsert) UpdateTokenContract() *USDTPaymentIntentUpsert {
	u.SetExcluded(usdtpaymentintent.FieldTokenContract)
	return u
}

// SetAmountUsdt sets the "amount_usdt" field.
func (u *USDTPaymentIntentUpsert) SetAmountUsdt(v string) *USDTPaymentIntentUpsert {
	u.Set(usdtpaymentintent.FieldAmountUsdt, v)
	return u
}

// UpdateAmountUsdt sets the "amount_usdt" field to the value that was provided on create.
func (u *USDTPaymentIntentUpsert) UpdateAmountUsdt() *USDTPaymentIntentUpsert {
	u.SetExcluded(usdtpaymentintent.FieldAmountUsdt)
	return u
}

// SetRate sets the "rate" field.
func (u *USDTPaymentIntentUpsert) SetRate(v string) *USDTPaymentIntentUpsert {
	u.Set(usdtpaymentintent.FieldRate, v)
	return u
}

// UpdateRate sets the "rate" field to the value that was provided on create.
func (u *USDTPaymentIntentUpsert) UpdateRate() *USDTPaymentIntentUpsert {
	u.SetExcluded(usdtpaymentintent.FieldRate)
	return u
}

// SetBaseRate sets the "base_rate" field.
func (u *USDTPaymentIntentUpsert) SetBaseRate(v string) *USDTPaymentIntentUpsert {
	u.Set(usdtpaymentintent.FieldBaseRate, v)
	return u
}

// UpdateBaseRate sets the "base_rate" field to the value that was provided on create.
func (u *USDTPaymentIntentUpsert) UpdateBaseRate() *USDTPaymentIntentUpsert {
	u.SetExcluded(usdtpaymentintent.FieldBaseRate)
	return u
}

// SetPremiumPercent sets the "premium_percent" field.
func (u *USDTPaymentIntentUpsert) SetPremiumPercent(v string) *USDTPaymentIntentUpsert {
	u.Set(usdtpaymentintent.FieldPremiumPercent, v)
	return u
}

// UpdatePremiumPercent sets the "premium_percent" field to the value that was provided on create.
func (u *USDTPaymentIntentUpsert) UpdatePremiumPercent() *USDTPaymentIntentUpsert {
	u.SetExcluded(usdtpaymentintent.FieldPremiumPercent)
	return u
}

// SetRateSource sets the "rate_source" field.
func (u *USDTPaymentIntentUpsert) SetRateSource(v string) *USDTPaymentIntentUpsert {
	u.Set(usdtpaymentintent.FieldRateSource, v)
	return u
}

// UpdateRateSource sets the "rate_source" field to the value that was provided on create.
func (u *USDTPaymentIntentUpsert) UpdateRateSource() *USDTPaymentIntentUpsert {
	u.SetExcluded(usdtpaymentintent.FieldRateSource)
	return u
}

// SetRateQuotedAt sets the "rate_quoted_at" field.
func (u *USDTPaymentIntentUpsert) SetRateQuotedAt(v time.Time) *USDTPaymentIntentUpsert {
	u.Set(usdtpaymentintent.FieldRateQuotedAt, v)
	return u
}

// UpdateRateQuotedAt sets the "rate_quoted_at" field to the value that was provided on create.
func (u *USDTPaymentIntentUpsert) UpdateRateQuotedAt() *USDTPaymentIntentUpsert {
	u.SetExcluded(usdtpaymentintent.FieldRateQuotedAt)
	return u
}

// SetStatus sets the "status" field.
func (u *USDTPaymentIntentUpsert) SetStatus(v string) *USDTPaymentIntentUpsert {
	u.Set(usdtpaymentintent.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *USDTPaymentIntentUpsert) UpdateStatus() *USDTPaymentIntentUpsert {
	u.SetExcluded(usdtpaymentintent.FieldStatus)
	return u
}

// SetMatchedTxHash sets the "matched_tx_hash" field.
func (u *USDTPaymentIntentUpsert) SetMatchedTxHash(v string) *USDTPaymentIntentUpsert {
	u.Set(usdtpaymentintent.FieldMatchedTxHash, v)
	return u
}

// UpdateMatchedTxHash sets the "matched_tx_hash" field to the value that was provided on create.
func (u *USDTPaymentIntentUpsert) UpdateMatchedTxHash() *USDTPaymentIntentUpsert {
	u.SetExcluded(usdtpaymentintent.FieldMatchedTxHash)
	return u
}

// ClearMatchedTxHash clears the value of the "matched_tx_hash" field.
func (u *USDTPaymentIntentUpsert) ClearMatchedTxHash() *USDTPaymentIntentUpsert {
	u.SetNull(usdtpaymentintent.FieldMatchedTxHash)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *USDTPaymentIntentUpsert) SetExpiresAt(v time.Time) *USDTPaymentIntentUpsert {
	u.Set(usdtpaymentintent.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *USDTPaymentIntentUpsert) UpdateExpiresAt() *USDTPaymentIntentUpsert {
	u.SetExcluded(usdtpaymentintent.FieldExpiresAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *USDTPaymentIntentUpsert) SetUpdatedAt(v time.Time) *USDTPaymentIntentUpsert {
	u.Set(usdtpaymentintent.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *USDTPaymentIntentUpsert) UpdateUpdatedAt() *USDTPaymentIntentUpsert {
	u.SetExcluded(usdtpaymentintent.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.USDTPaymentIntent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *USDTPaymentIntentUpsertOne) UpdateNewValues() *USDTPaymentIntentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(usdtpaymentintent.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.USDTPaymentIntent.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *USDTPaymentIntentUpsertOne) Ignore() *USDTPaymentIntentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *USDTPaymentIntentUpsertOne) DoNothing() *USDTPaymentIntentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the USDTPaymentIntentCreate.OnConflict
// documentation for more info.
func (u *USDTPaymentIntentUpsertOne) Update(set func(*USDTPaymentIntentUpsert)) *USDTPaymentIntentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&USDTPaymentIntentUpsert{UpdateSet: update})
	}))
	return u
}

// SetOrderID sets the "order_id" field.
func (u *USDTPaymentIntentUpsertOne) SetOrderID(v int64) *USDTPaymentIntentUpsertOne {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.SetOrderID(v)
	})
}

// AddOrderID adds v to the "order_id" field.
func (u *USDTPaymentIntentUpsertOne) AddOrderID(v int64) *USDTPaymentIntentUpsertOne {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.AddOrderID(v)
	})
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *USDTPaymentIntentUpsertOne) UpdateOrderID() *USDTPaymentIntentUpsertOne {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.UpdateOrderID()
	})
}

// SetOutTradeNo sets the "out_trade_no" field.
func (u *USDTPaymentIntentUpsertOne) SetOutTradeNo(v string) *USDTPaymentIntentUpsertOne {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.SetOutTradeNo(v)
	})
}

// UpdateOutTradeNo sets the "out_trade_no" field to the value that was provided on create.
func (u *USDTPaymentIntentUpsertOne) UpdateOutTradeNo() *USDTPaymentIntentUpsertOne {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.UpdateOutTradeNo()
	})
}

// SetProviderInstanceID sets the "provider_instance_id" field.
func (u *USDTPaymentIntentUpsertOne) SetProviderInstanceID(v string) *USDTPaymentIntentUpsertOne {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.SetProviderInstanceID(v)
	})
}

// UpdateProviderInstanceID sets the "provider_instance_id" field to the value that was provided on create.
func (u *USDTPaymentIntentUpsertOne) UpdateProviderInstanceID() *USDTPaymentIntentUpsertOne {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.UpdateProviderInstanceID()
	})
}

// SetAddress sets the "address" field.
func (u *USDTPaymentIntentUpsertOne) SetAddress(v string) *USDTPaymentIntentUpsertOne {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.SetAddress(v)
	})
}

// UpdateAddress sets the "address" field to the value that was provided on create.
func (u *USDTPaymentIntentUpsertOne) UpdateAddress() *USDTPaymentIntentUpsertOne {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.UpdateAddress()
	})
}

// SetNetwork sets the "network" field.
func (u *USDTPaymentIntentUpsertOne) SetNetwork(v string) *USDTPaymentIntentUpsertOne {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.SetNetwork(v)
	})
}

// UpdateNetwork sets the "network" field to the value that was provided on create.
func (u *USDTPaymentIntentUpsertOne) UpdateNetwork() *USDTPaymentIntentUpsertOne {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.UpdateNetwork()
	})
}

// SetTokenContract sets the "token_contract" field.
func (u *USDTPaymentIntentUpsertOne) SetTokenContract(v string) *USDTPaymentIntentUpsertOne {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.SetTokenContract(v)
	})
}

// UpdateTokenContract sets the "token_contract" field to the value that was provided on create.
func (u *USDTPaymentIntentUpsertOne) UpdateTokenContract() *USDTPaymentIntentUpsertOne {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.UpdateTokenContract()
	})
}

// SetAmountUsdt sets the "amount_usdt" field.
func (u *USDTPaymentIntentUpsertOne) SetAmountUsdt(v string) *USDTPaymentIntentUpsertOne {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.SetAmountUsdt(v)
	})
}

// UpdateAmountUsdt sets the "amount_usdt" field to the value that was provided on create.
func (u *USDTPaymentIntentUpsertOne) UpdateAmountUsdt() *USDTPaymentIntentUpsertOne {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.UpdateAmountUsdt()
	})
}

// SetRate sets the "rate" field.
func (u *USDTPaymentIntentUpsertOne) SetRate(v string) *USDTPaymentIntentUpsertOne {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.SetRate(v)
	})
}

// UpdateRate sets the "rate" field to the value that was provided on create.
func (u *USDTPaymentIntentUpsertOne) UpdateRate() *USDTPaymentIntentUpsertOne {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.UpdateRate()
	})
}

// SetBaseRate sets the "base_rate" field.
func (u *USDTPaymentIntentUpsertOne) SetBaseRate(v string) *USDTPaymentIntentUpsertOne {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.SetBaseRate(v)
	})
}

// UpdateBaseRate sets the "base_rate" field to the value that was provided on create.
func (u *USDTPaymentIntentUpsertOne) UpdateBaseRate() *USDTPaymentIntentUpsertOne {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.UpdateBaseRate()
	})
}

// SetPremiumPercent sets the "premium_percent" field.
func (u *USDTPaymentIntentUpsertOne) SetPremiumPercent(v string) *USDTPaymentIntentUpsertOne {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.SetPremiumPercent(v)
	})
}

// UpdatePremiumPercent sets the "premium_percent" field to the value that was provided on create.
func (u *USDTPaymentIntentUpsertOne) UpdatePremiumPercent() *USDTPaymentIntentUpsertOne {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.UpdatePremiumPercent()
	})
}

// SetRateSource sets the "rate_source" field.
func (u *USDTPaymentIntentUpsertOne) SetRateSource(v string) *USDTPaymentIntentUpsertOne {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.SetRateSource(v)
	})
}

// UpdateRateSource sets the "rate_source" field to the value that was provided on create.
func (u *USDTPaymentIntentUpsertOne) UpdateRateSource() *USDTPaymentIntentUpsertOne {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.UpdateRateSource()
	})
}

// SetRateQuotedAt sets the "rate_quoted_at" field.
func (u *USDTPaymentIntentUpsertOne) SetRateQuotedAt(v time.Time) *USDTPaymentIntentUpsertOne {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.SetRateQuotedAt(v)
	})
}

// UpdateRateQuotedAt sets the "rate_quoted_at" field to the value that was provided on create.
func (u *USDTPaymentIntentUpsertOne) UpdateRateQuotedAt() *USDTPaymentIntentUpsertOne {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.UpdateRateQuotedAt()
	})
}

// SetStatus sets the "status" field.
func (u *USDTPaymentIntentUpsertOne) SetStatus(v string) *USDTPaymentIntentUpsertOne {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *USDTPaymentIntentUpsertOne) UpdateStatus() *USDTPaymentIntentUpsertOne {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.UpdateStatus()
	})
}

// SetMatchedTxHash sets the "matched_tx_hash" field.
func (u *USDTPaymentIntentUpsertOne) SetMatchedTxHash(v string) *USDTPaymentIntentUpsertOne {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.SetMatchedTxHash(v)
	})
}

// UpdateMatchedTxHash sets the "matched_tx_hash" field to the value that was provided on create.
func (u *USDTPaymentIntentUpsertOne) UpdateMatchedTxHash() *USDTPaymentIntentUpsertOne {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.UpdateMatchedTxHash()
	})
}

// ClearMatchedTxHash clears the value of the "matched_tx_hash" field.
func (u *USDTPaymentIntentUpsertOne) ClearMatchedTxHash() *USDTPaymentIntentUpsertOne {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.ClearMatchedTxHash()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *USDTPaymentIntentUpsertOne) SetExpiresAt(v time.Time) *USDTPaymentIntentUpsertOne {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *USDTPaymentIntentUpsertOne) UpdateExpiresAt() *USDTPaymentIntentUpsertOne {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *USDTPaymentIntentUpsertOne) SetUpdatedAt(v time.Time) *USDTPaymentIntentUpsertOne {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *USDTPaymentIntentUpsertOne) UpdateUpdatedAt() *USDTPaymentIntentUpsertOne {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *USDTPaymentIntentUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for USDTPaymentIntentCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *USDTPaymentIntentUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *USDTPaymentIntentUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *USDTPaymentIntentUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// USDTPaymentIntentCreateBulk is the builder for creating many USDTPaymentIntent entities in bulk.
type USDTPaymentIntentCreateBulk struct {
	config
	err      error
	builders []*USDTPaymentIntentCreate
	conflict []sql.ConflictOption
}

// Save creates the USDTPaymentIntent entities in the database.
func (_c *USDTPaymentIntentCreateBulk) Save(ctx context.Context) ([]*USDTPaymentIntent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*USDTPaymentIntent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*USDTPaymentIntentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *USDTPaymentIntentCreateBulk) SaveX(ctx context.Context) []*USDTPaymentIntent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *USDTPaymentIntentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *USDTPaymentIntentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.USDTPaymentIntent.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.USDTPaymentIntentUpsert) {
//			SetOrderID(v+v).
//		}).
//		Exec(ctx)
func (_c *USDTPaymentIntentCreateBulk) OnConflict(opts ...sql.ConflictOption) *USDTPaymentIntentUpsertBulk {
	_c.conflict = opts
	return &USDTPaymentIntentUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.USDTPaymentIntent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *USDTPaymentIntentCreateBulk) OnConflictColumns(columns ...string) *USDTPaymentIntentUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &USDTPaymentIntentUpsertBulk{
		create: _c,
	}
}

// USDTPaymentIntentUpsertBulk is the builder for "upsert"-ing
// a bulk of USDTPaymentIntent nodes.
type USDTPaymentIntentUpsertBulk struct {
	create *USDTPaymentIntentCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.USDTPaymentIntent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *USDTPaymentIntentUpsertBulk) UpdateNewValues() *USDTPaymentIntentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(usdtpaymentintent.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.USDTPaymentIntent.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *USDTPaymentIntentUpsertBulk) Ignore() *USDTPaymentIntentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *USDTPaymentIntentUpsertBulk) DoNothing() *USDTPaymentIntentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the USDTPaymentIntentCreateBulk.OnConflict
// documentation for more info.
func (u *USDTPaymentIntentUpsertBulk) Update(set func(*USDTPaymentIntentUpsert)) *USDTPaymentIntentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&USDTPaymentIntentUpsert{UpdateSet: update})
	}))
	return u
}

// SetOrderID sets the "order_id" field.
func (u *USDTPaymentIntentUpsertBulk) SetOrderID(v int64) *USDTPaymentIntentUpsertBulk {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.SetOrderID(v)
	})
}

// AddOrderID adds v to the "order_id" field.
func (u *USDTPaymentIntentUpsertBulk) AddOrderID(v int64) *USDTPaymentIntentUpsertBulk {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.AddOrderID(v)
	})
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *USDTPaymentIntentUpsertBulk) UpdateOrderID() *USDTPaymentIntentUpsertBulk {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.UpdateOrderID()
	})
}

// SetOutTradeNo sets the "out_trade_no" field.
func (u *USDTPaymentIntentUpsertBulk) SetOutTradeNo(v string) *USDTPaymentIntentUpsertBulk {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.SetOutTradeNo(v)
	})
}

// UpdateOutTradeNo sets the "out_trade_no" field to the value that was provided on create.
func (u *USDTPaymentIntentUpsertBulk) UpdateOutTradeNo() *USDTPaymentIntentUpsertBulk {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.UpdateOutTradeNo()
	})
}

// SetProviderInstanceID sets the "provider_instance_id" field.
func (u *USDTPaymentIntentUpsertBulk) SetProviderInstanceID(v string) *USDTPaymentIntentUpsertBulk {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.SetProviderInstanceID(v)
	})
}

// UpdateProviderInstanceID sets the "provider_instance_id" field to the value that was provided on create.
func (u *USDTPaymentIntentUpsertBulk) UpdateProviderInstanceID() *USDTPaymentIntentUpsertBulk {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.UpdateProviderInstanceID()
	})
}

// SetAddress sets the "address" field.
func (u *USDTPaymentIntentUpsertBulk) SetAddress(v string) *USDTPaymentIntentUpsertBulk {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.SetAddress(v)
	})
}

// UpdateAddress sets the "address" field to the value that was provided on create.
func (u *USDTPaymentIntentUpsertBulk) UpdateAddress() *USDTPaymentIntentUpsertBulk {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.UpdateAddress()
	})
}

// SetNetwork sets the "network" field.
func (u *USDTPaymentIntentUpsertBulk) SetNetwork(v string) *USDTPaymentIntentUpsertBulk {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.SetNetwork(v)
	})
}

// UpdateNetwork sets the "network" field to the value that was provided on create.
func (u *USDTPaymentIntentUpsertBulk) UpdateNetwork() *USDTPaymentIntentUpsertBulk {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.UpdateNetwork()
	})
}

// SetTokenContract sets the "token_contract" field.
func (u *USDTPaymentIntentUpsertBulk) SetTokenContract(v string) *USDTPaymentIntentUpsertBulk {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.SetTokenContract(v)
	})
}

// UpdateTokenContract sets the "token_contract" field to the value that was provided on create.
func (u *USDTPaymentIntentUpsertBulk) UpdateTokenContract() *USDTPaymentIntentUpsertBulk {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.UpdateTokenContract()
	})
}

// SetAmountUsdt sets the "amount_usdt" field.
func (u *USDTPaymentIntentUpsertBulk) SetAmountUsdt(v string) *USDTPaymentIntentUpsertBulk {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.SetAmountUsdt(v)
	})
}

// UpdateAmountUsdt sets the "amount_usdt" field to the value that was provided on create.
func (u *USDTPaymentIntentUpsertBulk) UpdateAmountUsdt() *USDTPaymentIntentUpsertBulk {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.UpdateAmountUsdt()
	})
}

// SetRate sets the "rate" field.
func (u *USDTPaymentIntentUpsertBulk) SetRate(v string) *USDTPaymentIntentUpsertBulk {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.SetRate(v)
	})
}

// UpdateRate sets the "rate" field to the value that was provided on create.
func (u *USDTPaymentIntentUpsertBulk) UpdateRate() *USDTPaymentIntentUpsertBulk {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.UpdateRate()
	})
}

// SetBaseRate sets the "base_rate" field.
func (u *USDTPaymentIntentUpsertBulk) SetBaseRate(v string) *USDTPaymentIntentUpsertBulk {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.SetBaseRate(v)
	})
}

// UpdateBaseRate sets the "base_rate" field to the value that was provided on create.
func (u *USDTPaymentIntentUpsertBulk) UpdateBaseRate() *USDTPaymentIntentUpsertBulk {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.UpdateBaseRate()
	})
}

// SetPremiumPercent sets the "premium_percent" field.
func (u *USDTPaymentIntentUpsertBulk) SetPremiumPercent(v string) *USDTPaymentIntentUpsertBulk {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.SetPremiumPercent(v)
	})
}

// UpdatePremiumPercent sets the "premium_percent" field to the value that was provided on create.
func (u *USDTPaymentIntentUpsertBulk) UpdatePremiumPercent() *USDTPaymentIntentUpsertBulk {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.UpdatePremiumPercent()
	})
}

// SetRateSource sets the "rate_source" field.
func (u *USDTPaymentIntentUpsertBulk) SetRateSource(v string) *USDTPaymentIntentUpsertBulk {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.SetRateSource(v)
	})
}

// UpdateRateSource sets the "rate_source" field to the value that was provided on create.
func (u *USDTPaymentIntentUpsertBulk) UpdateRateSource() *USDTPaymentIntentUpsertBulk {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.UpdateRateSource()
	})
}

// SetRateQuotedAt sets the "rate_quoted_at" field.
func (u *USDTPaymentIntentUpsertBulk) SetRateQuotedAt(v time.Time) *USDTPaymentIntentUpsertBulk {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.SetRateQuotedAt(v)
	})
}

// UpdateRateQuotedAt sets the "rate_quoted_at" field to the value that was provided on create.
func (u *USDTPaymentIntentUpsertBulk) UpdateRateQuotedAt() *USDTPaymentIntentUpsertBulk {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.UpdateRateQuotedAt()
	})
}

// SetStatus sets the "status" field.
func (u *USDTPaymentIntentUpsertBulk) SetStatus(v string) *USDTPaymentIntentUpsertBulk {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *USDTPaymentIntentUpsertBulk) UpdateStatus() *USDTPaymentIntentUpsertBulk {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.UpdateStatus()
	})
}

// SetMatchedTxHash sets the "matched_tx_hash" field.
func (u *USDTPaymentIntentUpsertBulk) SetMatchedTxHash(v string) *USDTPaymentIntentUpsertBulk {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.SetMatchedTxHash(v)
	})
}

// UpdateMatchedTxHash sets the "matched_tx_hash" field to the value that was provided on create.
func (u *USDTPaymentIntentUpsertBulk) UpdateMatchedTxHash() *USDTPaymentIntentUpsertBulk {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.UpdateMatchedTxHash()
	})
}

// ClearMatchedTxHash clears the value of the "matched_tx_hash" field.
func (u *USDTPaymentIntentUpsertBulk) ClearMatchedTxHash() *USDTPaymentIntentUpsertBulk {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.ClearMatchedTxHash()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *USDTPaymentIntentUpsertBulk) SetExpiresAt(v time.Time) *USDTPaymentIntentUpsertBulk {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *USDTPaymentIntentUpsertBulk) UpdateExpiresAt() *USDTPaymentIntentUpsertBulk {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *USDTPaymentIntentUpsertBulk) SetUpdatedAt(v time.Time) *USDTPaymentIntentUpsertBulk {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *USDTPaymentIntentUpsertBulk) UpdateUpdatedAt() *USDTPaymentIntentUpsertBulk {
	return u.Update(func(s *USDTPaymentIntentUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *USDTPaymentIntentUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the USDTPaymentIntentCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for USDTPaymentIntentCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *USDTPaymentIntentUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
