// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/usdtdeposit"
)

// USDTDeposit is the model entity for the USDTDeposit schema.
type USDTDeposit struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// TxHash holds the value of the "tx_hash" field.
	TxHash string `json:"tx_hash,omitempty"`
	// Address holds the value of the "address" field.
	Address string `json:"address,omitempty"`
	// FromAddress holds the value of the "from_address" field.
	FromAddress string `json:"from_address,omitempty"`
	// TokenContract holds the value of the "token_contract" field.
	TokenContract string `json:"token_contract,omitempty"`
	// AmountUsdt holds the value of the "amount_usdt" field.
	AmountUsdt string `json:"amount_usdt,omitempty"`
	// BlockTimestamp holds the value of the "block_timestamp" field.
	BlockTimestamp time.Time `json:"block_timestamp,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// MatchedOrderID holds the value of the "matched_order_id" field.
	MatchedOrderID *int64 `json:"matched_order_id,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes *string `json:"notes,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*USDTDeposit) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usdtdeposit.FieldID, usdtdeposit.FieldMatchedOrderID:
			values[i] = new(sql.NullInt64)
		case usdtdeposit.FieldTxHash, usdtdeposit.FieldAddress, usdtdeposit.FieldFromAddress, usdtdeposit.FieldTokenContract, usdtdeposit.FieldAmountUsdt, usdtdeposit.FieldStatus, usdtdeposit.FieldNotes:
			values[i] = new(sql.NullString)
		case usdtdeposit.FieldBlockTimestamp, usdtdeposit.FieldCreatedAt, usdtdeposit.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the USDTDeposit fields.
func (_m *USDTDeposit) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usdtdeposit.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case usdtdeposit.FieldTxHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tx_hash", values[i])
			} else if value.Valid {
				_m.TxHash = value.String
			}
		case usdtdeposit.FieldAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field address", values[i])
			} else if value.Valid {
				_m.Address = value.String
			}
		case usdtdeposit.FieldFromAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field from_address", values[i])
			} else if value.Valid {
				_m.FromAddress = value.String
			}
		case usdtdeposit.FieldTokenContract:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token_contract", values[i])
			} else if value.Valid {
				_m.TokenContract = value.String
			}
		case usdtdeposit.FieldAmountUsdt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field amount_usdt", values[i])
			} else if value.Valid {
				_m.AmountUsdt = value.String
			}
		case usdtdeposit.FieldBlockTimestamp:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field block_timestamp", values[i])
			} else if value.Valid {
				_m.BlockTimestamp = value.Time
			}
		case usdtdeposit.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case usdtdeposit.FieldMatchedOrderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field matched_order_id", values[i])
			} else if value.Valid {
				_m.MatchedOrderID = new(int64)
				*_m.MatchedOrderID = value.Int64
			}
		case usdtdeposit.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = new(string)
				*_m.Notes = value.String
			}
		case usdtdeposit.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case usdtdeposit.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the USDTDeposit.
// This includes values selected through modifiers, order, etc.
func (_m *USDTDeposit) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this USDTDeposit.
// Note that you need to call USDTDeposit.Unwrap() before calling this method if this USDTDeposit
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *USDTDeposit) Update() *USDTDepositUpdateOne {
	return NewUSDTDepositClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the USDTDeposit entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *USDTDeposit) Unwrap() *USDTDeposit {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: USDTDeposit is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *USDTDeposit) String() string {
	var builder strings.Builder
	builder.WriteString("USDTDeposit(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tx_hash=")
	builder.WriteString(_m.TxHash)
	builder.WriteString(", ")
	builder.WriteString("address=")
	builder.WriteString(_m.Address)
	builder.WriteString(", ")
	builder.WriteString("from_address=")
	builder.WriteString(_m.FromAddress)
	builder.WriteString(", ")
	builder.WriteString("token_contract=")
	builder.WriteString(_m.TokenContract)
	builder.WriteString(", ")
	builder.WriteString("amount_usdt=")
	builder.WriteString(_m.AmountUsdt)
	builder.WriteString(", ")
	builder.WriteString("block_timestamp=")
	builder.WriteString(_m.BlockTimestamp.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.MatchedOrderID; v != nil {
		builder.WriteString("matched_order_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Notes; v != nil {
		builder.WriteString("notes=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// USDTDeposits is a parsable slice of USDTDeposit.
type USDTDeposits []*USDTDeposit
