// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/usdtdeposit"
)

// USDTDepositCreate is the builder for creating a USDTDeposit entity.
type USDTDepositCreate struct {
	config
	mutation *USDTDepositMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTxHash sets the "tx_hash" field.
func (_c *USDTDepositCreate) SetTxHash(v string) *USDTDepositCreate {
	_c.mutation.SetTxHash(v)
	return _c
}

// SetAddress sets the "address" field.
func (_c *USDTDepositCreate) SetAddress(v string) *USDTDepositCreate {
	_c.mutation.SetAddress(v)
	return _c
}

// SetFromAddress sets the "from_address" field.
func (_c *USDTDepositCreate) SetFromAddress(v string) *USDTDepositCreate {
	_c.mutation.SetFromAddress(v)
	return _c
}

// SetTokenContract sets the "token_contract" field.
func (_c *USDTDepositCreate) SetTokenContract(v string) *USDTDepositCreate {
	_c.mutation.SetTokenContract(v)
	return _c
}

// SetAmountUsdt sets the "amount_usdt" field.
func (_c *USDTDepositCreate) SetAmountUsdt(v string) *USDTDepositCreate {
	_c.mutation.SetAmountUsdt(v)
	return _c
}

// SetBlockTimestamp sets the "block_timestamp" field.
func (_c *USDTDepositCreate) SetBlockTimestamp(v time.Time) *USDTDepositCreate {
	_c.mutation.SetBlockTimestamp(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *USDTDepositCreate) SetStatus(v string) *USDTDepositCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *USDTDepositCreate) SetNillableStatus(v *string) *USDTDepositCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetMatchedOrderID sets the "matched_order_id" field.
func (_c *USDTDepositCreate) SetMatchedOrderID(v int64) *USDTDepositCreate {
	_c.mutation.SetMatchedOrderID(v)
	return _c
}

// SetNillableMatchedOrderID sets the "matched_order_id" field if the given value is not nil.
func (_c *USDTDepositCreate) SetNillableMatchedOrderID(v *int64) *USDTDepositCreate {
	if v != nil {
		_c.SetMatchedOrderID(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *USDTDepositCreate) SetNotes(v string) *USDTDepositCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *USDTDepositCreate) SetNillableNotes(v *string) *USDTDepositCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *USDTDepositCreate) SetCreatedAt(v time.Time) *USDTDepositCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *USDTDepositCreate) SetNillableCreatedAt(v *time.Time) *USDTDepositCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *USDTDepositCreate) SetUpdatedAt(v time.Time) *USDTDepositCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *USDTDepositCreate) SetNillableUpdatedAt(v *time.Time) *USDTDepositCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the USDTDepositMutation object of the builder.
func (_c *USDTDepositCreate) Mutation() *USDTDepositMutation {
	return _c.mutation
}

// Save creates the USDTDeposit in the database.
func (_c *USDTDepositCreate) Save(ctx context.Context) (*USDTDeposit, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *USDTDepositCreate) SaveX(ctx context.Context) *USDTDeposit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *USDTDepositCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *USDTDepositCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *USDTDepositCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := usdtdeposit.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := usdtdeposit.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := usdtdeposit.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *USDTDepositCreate) check() error {
	if _, ok := _c.mutation.TxHash(); !ok {
		return &ValidationError{Name: "tx_hash", err: errors.New(`ent: missing required field "USDTDeposit.tx_hash"`)}
	}
	if v, ok := _c.mutation.TxHash(); ok {
		if err := usdtdeposit.TxHashValidator(v); err != nil {
			return &ValidationError{Name: "tx_hash", err: fmt.Errorf(`ent: validator failed for field "USDTDeposit.tx_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Address(); !ok {
		return &ValidationError{Name: "address", err: errors.New(`ent: missing required field "USDTDeposit.address"`)}
	}
	if v, ok := _c.mutation.Address(); ok {
		if err := usdtdeposit.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "USDTDeposit.address": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FromAddress(); !ok {
		return &ValidationError{Name: "from_address", err: errors.New(`ent: missing required field "USDTDeposit.from_address"`)}
	}
	if v, ok := _c.mutation.FromAddress(); ok {
		if err := usdtdeposit.FromAddressValidator(v); err != nil {
			return &ValidationError{Name: "from_address", err: fmt.Errorf(`ent: validator failed for field "USDTDeposit.from_address": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TokenContract(); !ok {
		return &ValidationError{Name: "token_contract", err: errors.New(`ent: missing required field "USDTDeposit.token_contract"`)}
	}
	if v, ok := _c.mutation.TokenContract(); ok {
		if err := usdtdeposit.TokenContractValidator(v); err != nil {
			return &ValidationError{Name: "token_contract", err: fmt.Errorf(`ent: validator failed for field "USDTDeposit.token_contract": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AmountUsdt(); !ok {
		return &ValidationError{Name: "amount_usdt", err: errors.New(`ent: missing required field "USDTDeposit.amount_usdt"`)}
	}
	if v, ok := _c.mutation.AmountUsdt(); ok {
		if err := usdtdeposit.AmountUsdtValidator(v); err != nil {
			return &ValidationError{Name: "amount_usdt", err: fmt.Errorf(`ent: validator failed for field "USDTDeposit.amount_usdt": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BlockTimestamp(); !ok {
		return &ValidationError{Name: "block_timestamp", err: errors.New(`ent: missing required field "USDTDeposit.block_timestamp"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "USDTDeposit.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := usdtdeposit.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "USDTDeposit.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "USDTDeposit.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "USDTDeposit.updated_at"`)}
	}
	return nil
}

func (_c *USDTDepositCreate) sqlSave(ctx context.Context) (*USDTDeposit, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *USDTDepositCreate) createSpec() (*USDTDeposit, *sqlgraph.CreateSpec) {
	var (
		_node = &USDTDeposit{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(usdtdeposit.Table, sqlgraph.NewFieldSpec(usdtdeposit.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.TxHash(); ok {
		_spec.SetField(usdtdeposit.FieldTxHash, field.TypeString, value)
		_node.TxHash = value
	}
	if value, ok := _c.mutation.Address(); ok {
		_spec.SetField(usdtdeposit.FieldAddress, field.TypeString, value)
		_node.Address = value
	}
	if value, ok := _c.mutation.FromAddress(); ok {
		_spec.SetField(usdtdeposit.FieldFromAddress, field.TypeString, value)
		_node.FromAddress = value
	}
	if value, ok := _c.mutation.TokenContract(); ok {
		_spec.SetField(usdtdeposit.FieldTokenContract, field.TypeString, value)
		_node.TokenContract = value
	}
	if value, ok := _c.mutation.AmountUsdt(); ok {
		_spec.SetField(usdtdeposit.FieldAmountUsdt, field.TypeString, value)
		_node.AmountUsdt = value
	}
	if value, ok := _c.mutation.BlockTimestamp(); ok {
		_spec.SetField(usdtdeposit.FieldBlockTimestamp, field.TypeTime, value)
		_node.BlockTimestamp = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(usdtdeposit.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.MatchedOrderID(); ok {
		_spec.SetField(usdtdeposit.FieldMatchedOrderID, field.TypeInt64, value)
		_node.MatchedOrderID = &value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(usdtdeposit.FieldNotes, field.TypeString, value)
		_node.Notes = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(usdtdeposit.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(usdtdeposit.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.USDTDeposit.Create().
//		SetTxHash(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.USDTDepositUpsert) {
//			SetTxHash(v+v).
//		}).
//		Exec(ctx)
func (_c *USDTDepositCreate) OnConflict(opts ...sql.ConflictOption) *USDTDepositUpsertOne {
	_c.conflict = opts
	return &USDTDepositUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.USDTDeposit.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *USDTDepositCreate) OnConflictColumns(columns ...string) *USDTDepositUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &USDTDepositUpsertOne{
		create: _c,
	}
}

type (
	// USDTDepositUpsertOne is the builder for "upsert"-ing
	//  one USDTDeposit node.
	USDTDepositUpsertOne struct {
		create *USDTDepositCreate
	}

	// USDTDepositUpsert is the "OnConflict" setter.
	USDTDepositUpsert struct {
		*sql.UpdateSet
	}
)

// SetTxHash sets the "tx_hash" field.
func (u *USDTDepositUpsert) SetTxHash(v string) *USDTDepositUpsert {
	u.Set(usdtdeposit.FieldTxHash, v)
	return u
}

// UpdateTxHash sets the "tx_hash" field to the value that was provided on create.
func (u *USDTDepositUpsert) UpdateTxHash() *USDTDepositUpsert {
	u.SetExcluded(usdtdeposit.FieldTxHash)
	return u
}

// SetAddress sets the "address" field.
func (u *USDTDepositUpsert) SetAddress(v string) *USDTDepositUpsert {
	u.Set(usdtdeposit.FieldAddress, v)
	return u
}

// UpdateAddress sets the "address" field to the value that was provided on create.
func (u *USDTDepositUpsert) UpdateAddress() *USDTDepositUpsert {
	u.SetExcluded(usdtdeposit.FieldAddress)
	return u
}

// SetFromAddress sets the "from_address" field.
func (u *USDTDepositUpsert) SetFromAddress(v string) *USDTDepositUpsert {
	u.Set(usdtdeposit.FieldFromAddress, v)
	return u
}

// UpdateFromAddress sets the "from_address" field to the value that was provided on create.
func (u *USDTDepositUpsert) UpdateFromAddress() *USDTDepositUpsert {
	u.SetExcluded(usdtdeposit.FieldFromAddress)
	return u
}

// SetTokenContract sets the "token_contract" field.
func (u *USDTDepositUpsert) SetTokenContract(v string) *USDTDepositUpsert {
	u.Set(usdtdeposit.FieldTokenContract, v)
	return u
}

// UpdateTokenContract sets the "token_contract" field to the value that was provided on create.
func (u *USDTDepositUpsert) UpdateTokenContract() *USDTDepositUpsert {
	u.SetExcluded(usdtdeposit.FieldTokenContract)
	return u
}

// SetAmountUsdt sets the "amount_usdt" field.
func (u *USDTDepositUpsert) SetAmountUsdt(v string) *USDTDepositUpsert {
	u.Set(usdtdeposit.FieldAmountUsdt, v)
	return u
}

// UpdateAmountUsdt sets the "amount_usdt" field to the value that was provided on create.
func (u *USDTDepositUpsert) UpdateAmountUsdt() *USDTDepositUpsert {
	u.SetExcluded(usdtdeposit.FieldAmountUsdt)
	return u
}

// SetBlockTimestamp sets the "block_timestamp" field.
func (u *USDTDepositUpsert) SetBlockTimestamp(v time.Time) *USDTDepositUpsert {
	u.Set(usdtdeposit.FieldBlockTimestamp, v)
	return u
}

// UpdateBlockTimestamp sets the "block_timestamp" field to the value that was provided on create.
func (u *USDTDepositUpsert) UpdateBlockTimestamp() *USDTDepositUpsert {
	u.SetExcluded(usdtdeposit.FieldBlockTimestamp)
	return u
}

// SetStatus sets the "status" field.
func (u *USDTDepositUpsert) SetStatus(v string) *USDTDepositUpsert {
	u.Set(usdtdeposit.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *USDTDepositUpsert) UpdateStatus() *USDTDepositUpsert {
	u.SetExcluded(usdtdeposit.FieldStatus)
	return u
}

// SetMatchedOrderID sets the "matched_order_id" field.
func (u *USDTDepositUpsert) SetMatchedOrderID(v int64) *USDTDepositUpsert {
	u.Set(usdtdeposit.FieldMatchedOrderID, v)
	return u
}

// UpdateMatchedOrderID sets the "matched_order_id" field to the value that was provided on create.
func (u *USDTDepositUpsert) UpdateMatchedOrderID() *USDTDepositUpsert {
	u.SetExcluded(usdtdeposit.FieldMatchedOrderID)
	return u
}

// AddMatchedOrderID adds v to the "matched_order_id" field.
func (u *USDTDepositUpsert) AddMatchedOrderID(v int64) *USDTDepositUpsert {
	u.Add(usdtdeposit.FieldMatchedOrderID, v)
	return u
}

// ClearMatchedOrderID clears the value of the "matched_order_id" field.
func (u *USDTDepositUpsert) ClearMatchedOrderID() *USDTDepositUpsert {
	u.SetNull(usdtdeposit.FieldMatchedOrderID)
	return u
}

// SetNotes sets the "notes" field.
func (u *USDTDepositUpsert) SetNotes(v string) *USDTDepositUpsert {
	u.Set(usdtdeposit.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *USDTDepositUpsert) UpdateNotes() *USDTDepositUpsert {
	u.SetExcluded(usdtdeposit.FieldNotes)
	return u
}

// ClearNotes clears the value of the "notes" field.
func (u *USDTDepositUpsert) ClearNotes() *USDTDepositUpsert {
	u.SetNull(usdtdeposit.FieldNotes)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *USDTDepositUpsert) SetUpdatedAt(v time.Time) *USDTDepositUpsert {
	u.Set(usdtdeposit.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *USDTDepositUpsert) UpdateUpdatedAt() *USDTDepositUpsert {
	u.SetExcluded(usdtdeposit.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.USDTDeposit.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *USDTDepositUpsertOne) UpdateNewValues() *USDTDepositUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(usdtdeposit.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.USDTDeposit.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *USDTDepositUpsertOne) Ignore() *USDTDepositUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *USDTDepositUpsertOne) DoNothing() *USDTDepositUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the USDTDepositCreate.OnConflict
// documentation for more info.
func (u *USDTDepositUpsertOne) Update(set func(*USDTDepositUpsert)) *USDTDepositUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&USDTDepositUpsert{UpdateSet: update})
	}))
	return u
}

// SetTxHash sets the "tx_hash" field.
func (u *USDTDepositUpsertOne) SetTxHash(v string) *USDTDepositUpsertOne {
	return u.Update(func(s *USDTDepositUpsert) {
		s.SetTxHash(v)
	})
}

// UpdateTxHash sets the "tx_hash" field to the value that was provided on create.
func (u *USDTDepositUpsertOne) UpdateTxHash() *USDTDepositUpsertOne {
	return u.Update(func(s *USDTDepositUpsert) {
		s.UpdateTxHash()
	})
}

// SetAddress sets the "address" field.
func (u *USDTDepositUpsertOne) SetAddress(v string) *USDTDepositUpsertOne {
	return u.Update(func(s *USDTDepositUpsert) {
		s.SetAddress(v)
	})
}

// UpdateAddress sets the "address" field to the value that was provided on create.
func (u *USDTDepositUpsertOne) UpdateAddress() *USDTDepositUpsertOne {
	return u.Update(func(s *USDTDepositUpsert) {
		s.UpdateAddress()
	})
}

// SetFromAddress sets the "from_address" field.
func (u *USDTDepositUpsertOne) SetFromAddress(v string) *USDTDepositUpsertOne {
	return u.Update(func(s *USDTDepositUpsert) {
		s.SetFromAddress(v)
	})
}

// UpdateFromAddress sets the "from_address" field to the value that was provided on create.
func (u *USDTDepositUpsertOne) UpdateFromAddress() *USDTDepositUpsertOne {
	return u.Update(func(s *USDTDepositUpsert) {
		s.UpdateFromAddress()
	})
}

// SetTokenContract sets the "token_contract" field.
func (u *USDTDepositUpsertOne) SetTokenContract(v string) *USDTDepositUpsertOne {
	return u.Update(func(s *USDTDepositUpsert) {
		s.SetTokenContract(v)
	})
}

// UpdateTokenContract sets the "token_contract" field to the value that was provided on create.
func (u *USDTDepositUpsertOne) UpdateTokenContract() *USDTDepositUpsertOne {
	return u.Update(func(s *USDTDepositUpsert) {
		s.UpdateTokenContract()
	})
}

// SetAmountUsdt sets the "amount_usdt" field.
func (u *USDTDepositUpsertOne) SetAmountUsdt(v string) *USDTDepositUpsertOne {
	return u.Update(func(s *USDTDepositUpsert) {
		s.SetAmountUsdt(v)
	})
}

// UpdateAmountUsdt sets the "amount_usdt" field to the value that was provided on create.
func (u *USDTDepositUpsertOne) UpdateAmountUsdt() *USDTDepositUpsertOne {
	return u.Update(func(s *USDTDepositUpsert) {
		s.UpdateAmountUsdt()
	})
}

// SetBlockTimestamp sets the "block_timestamp" field.
func (u *USDTDepositUpsertOne) SetBlockTimestamp(v time.Time) *USDTDepositUpsertOne {
	return u.Update(func(s *USDTDepositUpsert) {
		s.SetBlockTimestamp(v)
	})
}

// UpdateBlockTimestamp sets the "block_timestamp" field to the value that was provided on create.
func (u *USDTDepositUpsertOne) UpdateBlockTimestamp() *USDTDepositUpsertOne {
	return u.Update(func(s *USDTDepositUpsert) {
		s.UpdateBlockTimestamp()
	})
}

// SetStatus sets the "status" field.
func (u *USDTDepositUpsertOne) SetStatus(v string) *USDTDepositUpsertOne {
	return u.Update(func(s *USDTDepositUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *USDTDepositUpsertOne) UpdateStatus() *USDTDepositUpsertOne {
	return u.Update(func(s *USDTDepositUpsert) {
		s.UpdateStatus()
	})
}

// SetMatchedOrderID sets the "matched_order_id" field.
func (u *USDTDepositUpsertOne) SetMatchedOrderID(v int64) *USDTDepositUpsertOne {
	return u.Update(func(s *USDTDepositUpsert) {
		s.SetMatchedOrderID(v)
	})
}

// AddMatchedOrderID adds v to the "matched_order_id" field.
func (u *USDTDepositUpsertOne) AddMatchedOrderID(v int64) *USDTDepositUpsertOne {
	return u.Update(func(s *USDTDepositUpsert) {
		s.AddMatchedOrderID(v)
	})
}

// UpdateMatchedOrderID sets the "matched_order_id" field to the value that was provided on create.
func (u *USDTDepositUpsertOne) UpdateMatchedOrderID() *USDTDepositUpsertOne {
	return u.Update(func(s *USDTDepositUpsert) {
		s.UpdateMatchedOrderID()
	})
}

// ClearMatchedOrderID clears the value of the "matched_order_id" field.
func (u *USDTDepositUpsertOne) ClearMatchedOrderID() *USDTDepositUpsertOne {
	return u.Update(func(s *USDTDepositUpsert) {
		s.ClearMatchedOrderID()
	})
}

// SetNotes sets the "notes" field.
func (u *USDTDepositUpsertOne) SetNotes(v string) *USDTDepositUpsertOne {
	return u.Update(func(s *USDTDepositUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *USDTDepositUpsertOne) UpdateNotes() *USDTDepositUpsertOne {
	return u.Update(func(s *USDTDepositUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *USDTDepositUpsertOne) ClearNotes() *USDTDepositUpsertOne {
	return u.Update(func(s *USDTDepositUpsert) {
		s.ClearNotes()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *USDTDepositUpsertOne) SetUpdatedAt(v time.Time) *USDTDepositUpsertOne {
	return u.Update(func(s *USDTDepositUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *USDTDepositUpsertOne) UpdateUpdatedAt() *USDTDepositUpsertOne {
	return u.Update(func(s *USDTDepositUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *USDTDepositUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for USDTDepositCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *USDTDepositUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *USDTDepositUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *USDTDepositUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// USDTDepositCreateBulk is the builder for creating many USDTDeposit entities in bulk.
type USDTDepositCreateBulk struct {
	config
	err      error
	builders []*USDTDepositCreate
	conflict []sql.ConflictOption
}

// Save creates the USDTDeposit entities in the database.
func (_c *USDTDepositCreateBulk) Save(ctx context.Context) ([]*USDTDeposit, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*USDTDeposit, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*USDTDepositMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *USDTDepositCreateBulk) SaveX(ctx context.Context) []*USDTDeposit {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *USDTDepositCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *USDTDepositCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.USDTDeposit.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.USDTDepositUpsert) {
//			SetTxHash(v+v).
//		}).
//		Exec(ctx)
func (_c *USDTDepositCreateBulk) OnConflict(opts ...sql.ConflictOption) *USDTDepositUpsertBulk {
	_c.conflict = opts
	return &USDTDepositUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.USDTDeposit.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *USDTDepositCreateBulk) OnConflictColumns(columns ...string) *USDTDepositUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &USDTDepositUpsertBulk{
		create: _c,
	}
}

// USDTDepositUpsertBulk is the builder for "upsert"-ing
// a bulk of USDTDeposit nodes.
type USDTDepositUpsertBulk struct {
	create *USDTDepositCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.USDTDeposit.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *USDTDepositUpsertBulk) UpdateNewValues() *USDTDepositUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(usdtdeposit.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.USDTDeposit.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *USDTDepositUpsertBulk) Ignore() *USDTDepositUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *USDTDepositUpsertBulk) DoNothing() *USDTDepositUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the USDTDepositCreateBulk.OnConflict
// documentation for more info.
func (u *USDTDepositUpsertBulk) Update(set func(*USDTDepositUpsert)) *USDTDepositUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&USDTDepositUpsert{UpdateSet: update})
	}))
	return u
}

// SetTxHash sets the "tx_hash" field.
func (u *USDTDepositUpsertBulk) SetTxHash(v string) *USDTDepositUpsertBulk {
	return u.Update(func(s *USDTDepositUpsert) {
		s.SetTxHash(v)
	})
}

// UpdateTxHash sets the "tx_hash" field to the value that was provided on create.
func (u *USDTDepositUpsertBulk) UpdateTxHash() *USDTDepositUpsertBulk {
	return u.Update(func(s *USDTDepositUpsert) {
		s.UpdateTxHash()
	})
}

// SetAddress sets the "address" field.
func (u *USDTDepositUpsertBulk) SetAddress(v string) *USDTDepositUpsertBulk {
	return u.Update(func(s *USDTDepositUpsert) {
		s.SetAddress(v)
	})
}

// UpdateAddress sets the "address" field to the value that was provided on create.
func (u *USDTDepositUpsertBulk) UpdateAddress() *USDTDepositUpsertBulk {
	return u.Update(func(s *USDTDepositUpsert) {
		s.UpdateAddress()
	})
}

// SetFromAddress sets the "from_address" field.
func (u *USDTDepositUpsertBulk) SetFromAddress(v string) *USDTDepositUpsertBulk {
	return u.Update(func(s *USDTDepositUpsert) {
		s.SetFromAddress(v)
	})
}

// UpdateFromAddress sets the "from_address" field to the value that was provided on create.
func (u *USDTDepositUpsertBulk) UpdateFromAddress() *USDTDepositUpsertBulk {
	return u.Update(func(s *USDTDepositUpsert) {
		s.UpdateFromAddress()
	})
}

// SetTokenContract sets the "token_contract" field.
func (u *USDTDepositUpsertBulk) SetTokenContract(v string) *USDTDepositUpsertBulk {
	return u.Update(func(s *USDTDepositUpsert) {
		s.SetTokenContract(v)
	})
}

// UpdateTokenContract sets the "token_contract" field to the value that was provided on create.
func (u *USDTDepositUpsertBulk) UpdateTokenContract() *USDTDepositUpsertBulk {
	return u.Update(func(s *USDTDepositUpsert) {
		s.UpdateTokenContract()
	})
}

// SetAmountUsdt sets the "amount_usdt" field.
func (u *USDTDepositUpsertBulk) SetAmountUsdt(v string) *USDTDepositUpsertBulk {
	return u.Update(func(s *USDTDepositUpsert) {
		s.SetAmountUsdt(v)
	})
}

// UpdateAmountUsdt sets the "amount_usdt" field to the value that was provided on create.
func (u *USDTDepositUpsertBulk) UpdateAmountUsdt() *USDTDepositUpsertBulk {
	return u.Update(func(s *USDTDepositUpsert) {
		s.UpdateAmountUsdt()
	})
}

// SetBlockTimestamp sets the "block_timestamp" field.
func (u *USDTDepositUpsertBulk) SetBlockTimestamp(v time.Time) *USDTDepositUpsertBulk {
	return u.Update(func(s *USDTDepositUpsert) {
		s.SetBlockTimestamp(v)
	})
}

// UpdateBlockTimestamp sets the "block_timestamp" field to the value that was provided on create.
func (u *USDTDepositUpsertBulk) UpdateBlockTimestamp() *USDTDepositUpsertBulk {
	return u.Update(func(s *USDTDepositUpsert) {
		s.UpdateBlockTimestamp()
	})
}

// SetStatus sets the "status" field.
func (u *USDTDepositUpsertBulk) SetStatus(v string) *USDTDepositUpsertBulk {
	return u.Update(func(s *USDTDepositUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *USDTDepositUpsertBulk) UpdateStatus() *USDTDepositUpsertBulk {
	return u.Update(func(s *USDTDepositUpsert) {
		s.UpdateStatus()
	})
}

// SetMatchedOrderID sets the "matched_order_id" field.
func (u *USDTDepositUpsertBulk) SetMatchedOrderID(v int64) *USDTDepositUpsertBulk {
	return u.Update(func(s *USDTDepositUpsert) {
		s.SetMatchedOrderID(v)
	})
}

// AddMatchedOrderID adds v to the "matched_order_id" field.
func (u *USDTDepositUpsertBulk) AddMatchedOrderID(v int64) *USDTDepositUpsertBulk {
	return u.Update(func(s *USDTDepositUpsert) {
		s.AddMatchedOrderID(v)
	})
}

// UpdateMatchedOrderID sets the "matched_order_id" field to the value that was provided on create.
func (u *USDTDepositUpsertBulk) UpdateMatchedOrderID() *USDTDepositUpsertBulk {
	return u.Update(func(s *USDTDepositUpsert) {
		s.UpdateMatchedOrderID()
	})
}

// ClearMatchedOrderID clears the value of the "matched_order_id" field.
func (u *USDTDepositUpsertBulk) ClearMatchedOrderID() *USDTDepositUpsertBulk {
	return u.Update(func(s *USDTDepositUpsert) {
		s.ClearMatchedOrderID()
	})
}

// SetNotes sets the "notes" field.
func (u *USDTDepositUpsertBulk) SetNotes(v string) *USDTDepositUpsertBulk {
	return u.Update(func(s *USDTDepositUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *USDTDepositUpsertBulk) UpdateNotes() *USDTDepositUpsertBulk {
	return u.Update(func(s *USDTDepositUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *USDTDepositUpsertBulk) ClearNotes() *USDTDepositUpsertBulk {
	return u.Update(func(s *USDTDepositUpsert) {
		s.ClearNotes()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *USDTDepositUpsertBulk) SetUpdatedAt(v time.Time) *USDTDepositUpsertBulk {
	return u.Update(func(s *USDTDepositUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *USDTDepositUpsertBulk) UpdateUpdatedAt() *USDTDepositUpsertBulk {
	return u.Update(func(s *USDTDepositUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *USDTDepositUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the USDTDepositCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for USDTDepositCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *USDTDepositUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
