// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/usdtpaymentintent"
)

// USDTPaymentIntentDelete is the builder for deleting a USDTPaymentIntent entity.
type USDTPaymentIntentDelete struct {
	config
	hooks    []Hook
	mutation *USDTPaymentIntentMutation
}

// Where appends a list predicates to the USDTPaymentIntentDelete builder.
func (_d *USDTPaymentIntentDelete) Where(ps ...predicate.USDTPaymentIntent) *USDTPaymentIntentDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *USDTPaymentIntentDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *USDTPaymentIntentDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *USDTPaymentIntentDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(usdtpaymentintent.Table, sqlgraph.NewFieldSpec(usdtpaymentintent.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// USDTPaymentIntentDeleteOne is the builder for deleting a single USDTPaymentIntent entity.
type USDTPaymentIntentDeleteOne struct {
	_d *USDTPaymentIntentDelete
}

// Where appends a list predicates to the USDTPaymentIntentDelete builder.
func (_d *USDTPaymentIntentDeleteOne) Where(ps ...predicate.USDTPaymentIntent) *USDTPaymentIntentDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *USDTPaymentIntentDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{usdtpaymentintent.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *USDTPaymentIntentDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
