// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/usdtpaymentintent"
)

// USDTPaymentIntent is the model entity for the USDTPaymentIntent schema.
type USDTPaymentIntent struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// OrderID holds the value of the "order_id" field.
	OrderID int64 `json:"order_id,omitempty"`
	// OutTradeNo holds the value of the "out_trade_no" field.
	OutTradeNo string `json:"out_trade_no,omitempty"`
	// ProviderInstanceID holds the value of the "provider_instance_id" field.
	ProviderInstanceID string `json:"provider_instance_id,omitempty"`
	// Address holds the value of the "address" field.
	Address string `json:"address,omitempty"`
	// Network holds the value of the "network" field.
	Network string `json:"network,omitempty"`
	// TokenContract holds the value of the "token_contract" field.
	TokenContract string `json:"token_contract,omitempty"`
	// AmountUsdt holds the value of the "amount_usdt" field.
	AmountUsdt string `json:"amount_usdt,omitempty"`
	// Rate holds the value of the "rate" field.
	Rate string `json:"rate,omitempty"`
	// BaseRate holds the value of the "base_rate" field.
	BaseRate string `json:"base_rate,omitempty"`
	// PremiumPercent holds the value of the "premium_percent" field.
	PremiumPercent string `json:"premium_percent,omitempty"`
	// RateSource holds the value of the "rate_source" field.
	RateSource string `json:"rate_source,omitempty"`
	// RateQuotedAt holds the value of the "rate_quoted_at" field.
	RateQuotedAt time.Time `json:"rate_quoted_at,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// MatchedTxHash holds the value of the "matched_tx_hash" field.
	MatchedTxHash *string `json:"matched_tx_hash,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*USDTPaymentIntent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usdtpaymentintent.FieldID, usdtpaymentintent.FieldOrderID:
			values[i] = new(sql.NullInt64)
		case usdtpaymentintent.FieldOutTradeNo, usdtpaymentintent.FieldProviderInstanceID, usdtpaymentintent.FieldAddress, usdtpaymentintent.FieldNetwork, usdtpaymentintent.FieldTokenContract, usdtpaymentintent.FieldAmountUsdt, usdtpaymentintent.FieldRate, usdtpaymentintent.FieldBaseRate, usdtpaymentintent.FieldPremiumPercent, usdtpaymentintent.FieldRateSource, usdtpaymentintent.FieldStatus, usdtpaymentintent.FieldMatchedTxHash:
			values[i] = new(sql.NullString)
		case usdtpaymentintent.FieldRateQuotedAt, usdtpaymentintent.FieldExpiresAt, usdtpaymentintent.FieldCreatedAt, usdtpaymentintent.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the USDTPaymentIntent fields.
func (_m *USDTPaymentIntent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usdtpaymentintent.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case usdtpaymentintent.FieldOrderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field order_id", values[i])
			} else if value.Valid {
				_m.OrderID = value.Int64
			}
		case usdtpaymentintent.FieldOutTradeNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field out_trade_no", values[i])
			} else if value.Valid {
				_m.OutTradeNo = value.String
			}
		case usdtpaymentintent.FieldProviderInstanceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_instance_id", values[i])
			} else if value.Valid {
				_m.ProviderInstanceID = value.String
			}
		case usdtpaymentintent.FieldAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field address", values[i])
			} else if value.Valid {
				_m.Address = value.String
			}
		case usdtpaymentintent.FieldNetwork:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field network", values[i])
			} else if value.Valid {
				_m.Network = value.String
			}
		case usdtpaymentintent.FieldTokenContract:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token_contract", values[i])
			} else if value.Valid {
				_m.TokenContract = value.String
			}
		case usdtpaymentintent.FieldAmountUsdt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field amount_usdt", values[i])
			} else if value.Valid {
				_m.AmountUsdt = value.String
			}
		case usdtpaymentintent.FieldRate:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rate", values[i])
			} else if value.Valid {
				_m.Rate = value.String
			}
		case usdtpaymentintent.FieldBaseRate:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field base_rate", values[i])
			} else if value.Valid {
				_m.BaseRate = value.String
			}
		case usdtpaymentintent.FieldPremiumPercent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field premium_percent", values[i])
			} else if value.Valid {
				_m.PremiumPercent = value.String
			}
		case usdtpaymentintent.FieldRateSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rate_source", values[i])
			} else if value.Valid {
				_m.RateSource = value.String
			}
		case usdtpaymentintent.FieldRateQuotedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field rate_quoted_at", values[i])
			} else if value.Valid {
				_m.RateQuotedAt = value.Time
			}
		case usdtpaymentintent.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case usdtpaymentintent.FieldMatchedTxHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field matched_tx_hash", values[i])
			} else if value.Valid {
				_m.MatchedTxHash = new(string)
				*_m.MatchedTxHash = value.String
			}
		case usdtpaymentintent.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case usdtpaymentintent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case usdtpaymentintent.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the USDTPaymentIntent.
// This includes values selected through modifiers, order, etc.
func (_m *USDTPaymentIntent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this USDTPaymentIntent.
// Note that you need to call USDTPaymentIntent.Unwrap() before calling this method if this USDTPaymentIntent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *USDTPaymentIntent) Update() *USDTPaymentIntentUpdateOne {
	return NewUSDTPaymentIntentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the USDTPaymentIntent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *USDTPaymentIntent) Unwrap() *USDTPaymentIntent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: USDTPaymentIntent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *USDTPaymentIntent) String() string {
	var builder strings.Builder
	builder.WriteString("USDTPaymentIntent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("order_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OrderID))
	builder.WriteString(", ")
	builder.WriteString("out_trade_no=")
	builder.WriteString(_m.OutTradeNo)
	builder.WriteString(", ")
	builder.WriteString("provider_instance_id=")
	builder.WriteString(_m.ProviderInstanceID)
	builder.WriteString(", ")
	builder.WriteString("address=")
	builder.WriteString(_m.Address)
	builder.WriteString(", ")
	builder.WriteString("network=")
	builder.WriteString(_m.Network)
	builder.WriteString(", ")
	builder.WriteString("token_contract=")
	builder.WriteString(_m.TokenContract)
	builder.WriteString(", ")
	builder.WriteString("amount_usdt=")
	builder.WriteString(_m.AmountUsdt)
	builder.WriteString(", ")
	builder.WriteString("rate=")
	builder.WriteString(_m.Rate)
	builder.WriteString(", ")
	builder.WriteString("base_rate=")
	builder.WriteString(_m.BaseRate)
	builder.WriteString(", ")
	builder.WriteString("premium_percent=")
	builder.WriteString(_m.PremiumPercent)
	builder.WriteString(", ")
	builder.WriteString("rate_source=")
	builder.WriteString(_m.RateSource)
	builder.WriteString(", ")
	builder.WriteString("rate_quoted_at=")
	builder.WriteString(_m.RateQuotedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.MatchedTxHash; v != nil {
		builder.WriteString("matched_tx_hash=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// USDTPaymentIntents is a parsable slice of USDTPaymentIntent.
type USDTPaymentIntents []*USDTPaymentIntent
