// Code generated by ent, DO NOT EDIT.

package usdtdeposit

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the usdtdeposit type in the database.
	Label = "usdt_deposit"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTxHash holds the string denoting the tx_hash field in the database.
	FieldTxHash = "tx_hash"
	// FieldAddress holds the string denoting the address field in the database.
	FieldAddress = "address"
	// FieldFromAddress holds the string denoting the from_address field in the database.
	FieldFromAddress = "from_address"
	// FieldTokenContract holds the string denoting the token_contract field in the database.
	FieldTokenContract = "token_contract"
	// FieldAmountUsdt holds the string denoting the amount_usdt field in the database.
	FieldAmountUsdt = "amount_usdt"
	// FieldBlockTimestamp holds the string denoting the block_timestamp field in the database.
	FieldBlockTimestamp = "block_timestamp"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldMatchedOrderID holds the string denoting the matched_order_id field in the database.
	FieldMatchedOrderID = "matched_order_id"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the usdtdeposit in the database.
	Table = "usdt_deposits"
)

// Columns holds all SQL columns for usdtdeposit fields.
var Columns = []string{
	FieldID,
	FieldTxHash,
	FieldAddress,
	FieldFromAddress,
	FieldTokenContract,
	FieldAmountUsdt,
	FieldBlockTimestamp,
	FieldStatus,
	FieldMatchedOrderID,
	FieldNotes,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TxHashValidator is a validator for the "tx_hash" field. It is called by the builders before save.
	TxHashValidator func(string) error
	// AddressValidator is a validator for the "address" field. It is called by the builders before save.
	AddressValidator func(string) error
	// FromAddressValidator is a validator for the "from_address" field. It is called by the builders before save.
	FromAddressValidator func(string) error
	// TokenContractValidator is a validator for the "token_contract" field. It is called by the builders before save.
	TokenContractValidator func(string) error
	// AmountUsdtValidator is a validator for the "amount_usdt" field. It is called by the builders before save.
	AmountUsdtValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the USDTDeposit queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTxHash orders the results by the tx_hash field.
func ByTxHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTxHash, opts...).ToFunc()
}

// ByAddress orders the results by the address field.
func ByAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAddress, opts...).ToFunc()
}

// ByFromAddress orders the results by the from_address field.
func ByFromAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFromAddress, opts...).ToFunc()
}

// ByTokenContract orders the results by the token_contract field.
func ByTokenContract(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokenContract, opts...).ToFunc()
}

// ByAmountUsdt orders the results by the amount_usdt field.
func ByAmountUsdt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmountUsdt, opts...).ToFunc()
}

// ByBlockTimestamp orders the results by the block_timestamp field.
func ByBlockTimestamp(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBlockTimestamp, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByMatchedOrderID orders the results by the matched_order_id field.
func ByMatchedOrderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMatchedOrderID, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
