// Code generated by ent, DO NOT EDIT.

package usdtdeposit

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldLTE(FieldID, id))
}

// TxHash applies equality check predicate on the "tx_hash" field. It's identical to TxHashEQ.
func TxHash(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldEQ(FieldTxHash, v))
}

// Address applies equality check predicate on the "address" field. It's identical to AddressEQ.
func Address(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldEQ(FieldAddress, v))
}

// FromAddress applies equality check predicate on the "from_address" field. It's identical to FromAddressEQ.
func FromAddress(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldEQ(FieldFromAddress, v))
}

// TokenContract applies equality check predicate on the "token_contract" field. It's identical to TokenContractEQ.
func TokenContract(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldEQ(FieldTokenContract, v))
}

// AmountUsdt applies equality check predicate on the "amount_usdt" field. It's identical to AmountUsdtEQ.
func AmountUsdt(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldEQ(FieldAmountUsdt, v))
}

// BlockTimestamp applies equality check predicate on the "block_timestamp" field. It's identical to BlockTimestampEQ.
func BlockTimestamp(v time.Time) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldEQ(FieldBlockTimestamp, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldEQ(FieldStatus, v))
}

// MatchedOrderID applies equality check predicate on the "matched_order_id" field. It's identical to MatchedOrderIDEQ.
func MatchedOrderID(v int64) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldEQ(FieldMatchedOrderID, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldEQ(FieldNotes, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldEQ(FieldUpdatedAt, v))
}

// TxHashEQ applies the EQ predicate on the "tx_hash" field.
func TxHashEQ(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldEQ(FieldTxHash, v))
}

// TxHashNEQ applies the NEQ predicate on the "tx_hash" field.
func TxHashNEQ(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldNEQ(FieldTxHash, v))
}

// TxHashIn applies the In predicate on the "tx_hash" field.
func TxHashIn(vs ...string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldIn(FieldTxHash, vs...))
}

// TxHashNotIn applies the NotIn predicate on the "tx_hash" field.
func TxHashNotIn(vs ...string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldNotIn(FieldTxHash, vs...))
}

// TxHashGT applies the GT predicate on the "tx_hash" field.
func TxHashGT(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldGT(FieldTxHash, v))
}

// TxHashGTE applies the GTE predicate on the "tx_hash" field.
func TxHashGTE(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldGTE(FieldTxHash, v))
}

// TxHashLT applies the LT predicate on the "tx_hash" field.
func TxHashLT(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldLT(FieldTxHash, v))
}

// TxHashLTE applies the LTE predicate on the "tx_hash" field.
func TxHashLTE(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldLTE(FieldTxHash, v))
}

// TxHashContains applies the Contains predicate on the "tx_hash" field.
func TxHashContains(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldContains(FieldTxHash, v))
}

// TxHashHasPrefix applies the HasPrefix predicate on the "tx_hash" field.
func TxHashHasPrefix(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldHasPrefix(FieldTxHash, v))
}

// TxHashHasSuffix applies the HasSuffix predicate on the "tx_hash" field.
func TxHashHasSuffix(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldHasSuffix(FieldTxHash, v))
}

// TxHashEqualFold applies the EqualFold predicate on the "tx_hash" field.
func TxHashEqualFold(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldEqualFold(FieldTxHash, v))
}

// TxHashContainsFold applies the ContainsFold predicate on the "tx_hash" field.
func TxHashContainsFold(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldContainsFold(FieldTxHash, v))
}

// AddressEQ applies the EQ predicate on the "address" field.
func AddressEQ(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldEQ(FieldAddress, v))
}

// AddressNEQ applies the NEQ predicate on the "address" field.
func AddressNEQ(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldNEQ(FieldAddress, v))
}

// AddressIn applies the In predicate on the "address" field.
func AddressIn(vs ...string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldIn(FieldAddress, vs...))
}

// AddressNotIn applies the NotIn predicate on the "address" field.
func AddressNotIn(vs ...string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldNotIn(FieldAddress, vs...))
}

// AddressGT applies the GT predicate on the "address" field.
func AddressGT(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldGT(FieldAddress, v))
}

// AddressGTE applies the GTE predicate on the "address" field.
func AddressGTE(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldGTE(FieldAddress, v))
}

// AddressLT applies the LT predicate on the "address" field.
func AddressLT(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldLT(FieldAddress, v))
}

// AddressLTE applies the LTE predicate on the "address" field.
func AddressLTE(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldLTE(FieldAddress, v))
}

// AddressContains applies the Contains predicate on the "address" field.
func AddressContains(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldContains(FieldAddress, v))
}

// AddressHasPrefix applies the HasPrefix predicate on the "address" field.
func AddressHasPrefix(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldHasPrefix(FieldAddress, v))
}

// AddressHasSuffix applies the HasSuffix predicate on the "address" field.
func AddressHasSuffix(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldHasSuffix(FieldAddress, v))
}

// AddressEqualFold applies the EqualFold predicate on the "address" field.
func AddressEqualFold(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldEqualFold(FieldAddress, v))
}

// AddressContainsFold applies the ContainsFold predicate on the "address" field.
func AddressContainsFold(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldContainsFold(FieldAddress, v))
}

// FromAddressEQ applies the EQ predicate on the "from_address" field.
func FromAddressEQ(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldEQ(FieldFromAddress, v))
}

// FromAddressNEQ applies the NEQ predicate on the "from_address" field.
func FromAddressNEQ(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldNEQ(FieldFromAddress, v))
}

// FromAddressIn applies the In predicate on the "from_address" field.
func FromAddressIn(vs ...string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldIn(FieldFromAddress, vs...))
}

// FromAddressNotIn applies the NotIn predicate on the "from_address" field.
func FromAddressNotIn(vs ...string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldNotIn(FieldFromAddress, vs...))
}

// FromAddressGT applies the GT predicate on the "from_address" field.
func FromAddressGT(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldGT(FieldFromAddress, v))
}

// FromAddressGTE applies the GTE predicate on the "from_address" field.
func FromAddressGTE(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldGTE(FieldFromAddress, v))
}

// FromAddressLT applies the LT predicate on the "from_address" field.
func FromAddressLT(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldLT(FieldFromAddress, v))
}

// FromAddressLTE applies the LTE predicate on the "from_address" field.
func FromAddressLTE(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldLTE(FieldFromAddress, v))
}

// FromAddressContains applies the Contains predicate on the "from_address" field.
func FromAddressContains(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldContains(FieldFromAddress, v))
}

// FromAddressHasPrefix applies the HasPrefix predicate on the "from_address" field.
func FromAddressHasPrefix(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldHasPrefix(FieldFromAddress, v))
}

// FromAddressHasSuffix applies the HasSuffix predicate on the "from_address" field.
func FromAddressHasSuffix(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldHasSuffix(FieldFromAddress, v))
}

// FromAddressEqualFold applies the EqualFold predicate on the "from_address" field.
func FromAddressEqualFold(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldEqualFold(FieldFromAddress, v))
}

// FromAddressContainsFold applies the ContainsFold predicate on the "from_address" field.
func FromAddressContainsFold(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldContainsFold(FieldFromAddress, v))
}

// TokenContractEQ applies the EQ predicate on the "token_contract" field.
func TokenContractEQ(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldEQ(FieldTokenContract, v))
}

// TokenContractNEQ applies the NEQ predicate on the "token_contract" field.
func TokenContractNEQ(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldNEQ(FieldTokenContract, v))
}

// TokenContractIn applies the In predicate on the "token_contract" field.
func TokenContractIn(vs ...string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldIn(FieldTokenContract, vs...))
}

// TokenContractNotIn applies the NotIn predicate on the "token_contract" field.
func TokenContractNotIn(vs ...string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldNotIn(FieldTokenContract, vs...))
}

// TokenContractGT applies the GT predicate on the "token_contract" field.
func TokenContractGT(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldGT(FieldTokenContract, v))
}

// TokenContractGTE applies the GTE predicate on the "token_contract" field.
func TokenContractGTE(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldGTE(FieldTokenContract, v))
}

// TokenContractLT applies the LT predicate on the "token_contract" field.
func TokenContractLT(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldLT(FieldTokenContract, v))
}

// TokenContractLTE applies the LTE predicate on the "token_contract" field.
func TokenContractLTE(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldLTE(FieldTokenContract, v))
}

// TokenContractContains applies the Contains predicate on the "token_contract" field.
func TokenContractContains(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldContains(FieldTokenContract, v))
}

// TokenContractHasPrefix applies the HasPrefix predicate on the "token_contract" field.
func TokenContractHasPrefix(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldHasPrefix(FieldTokenContract, v))
}

// TokenContractHasSuffix applies the HasSuffix predicate on the "token_contract" field.
func TokenContractHasSuffix(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldHasSuffix(FieldTokenContract, v))
}

// TokenContractEqualFold applies the EqualFold predicate on the "token_contract" field.
func TokenContractEqualFold(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldEqualFold(FieldTokenContract, v))
}

// TokenContractContainsFold applies the ContainsFold predicate on the "token_contract" field.
func TokenContractContainsFold(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldContainsFold(FieldTokenContract, v))
}

// AmountUsdtEQ applies the EQ predicate on the "amount_usdt" field.
func AmountUsdtEQ(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldEQ(FieldAmountUsdt, v))
}

// AmountUsdtNEQ applies the NEQ predicate on the "amount_usdt" field.
func AmountUsdtNEQ(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldNEQ(FieldAmountUsdt, v))
}

// AmountUsdtIn applies the In predicate on the "amount_usdt" field.
func AmountUsdtIn(vs ...string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldIn(FieldAmountUsdt, vs...))
}

// AmountUsdtNotIn applies the NotIn predicate on the "amount_usdt" field.
func AmountUsdtNotIn(vs ...string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldNotIn(FieldAmountUsdt, vs...))
}

// AmountUsdtGT applies the GT predicate on the "amount_usdt" field.
func AmountUsdtGT(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldGT(FieldAmountUsdt, v))
}

// AmountUsdtGTE applies the GTE predicate on the "amount_usdt" field.
func AmountUsdtGTE(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldGTE(FieldAmountUsdt, v))
}

// AmountUsdtLT applies the LT predicate on the "amount_usdt" field.
func AmountUsdtLT(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldLT(FieldAmountUsdt, v))
}

// AmountUsdtLTE applies the LTE predicate on the "amount_usdt" field.
func AmountUsdtLTE(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldLTE(FieldAmountUsdt, v))
}

// AmountUsdtContains applies the Contains predicate on the "amount_usdt" field.
func AmountUsdtContains(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldContains(FieldAmountUsdt, v))
}

// AmountUsdtHasPrefix applies the HasPrefix predicate on the "amount_usdt" field.
func AmountUsdtHasPrefix(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldHasPrefix(FieldAmountUsdt, v))
}

// AmountUsdtHasSuffix applies the HasSuffix predicate on the "amount_usdt" field.
func AmountUsdtHasSuffix(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldHasSuffix(FieldAmountUsdt, v))
}

// AmountUsdtEqualFold applies the EqualFold predicate on the "amount_usdt" field.
func AmountUsdtEqualFold(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldEqualFold(FieldAmountUsdt, v))
}

// AmountUsdtContainsFold applies the ContainsFold predicate on the "amount_usdt" field.
func AmountUsdtContainsFold(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldContainsFold(FieldAmountUsdt, v))
}

// BlockTimestampEQ applies the EQ predicate on the "block_timestamp" field.
func BlockTimestampEQ(v time.Time) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldEQ(FieldBlockTimestamp, v))
}

// BlockTimestampNEQ applies the NEQ predicate on the "block_timestamp" field.
func BlockTimestampNEQ(v time.Time) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldNEQ(FieldBlockTimestamp, v))
}

// BlockTimestampIn applies the In predicate on the "block_timestamp" field.
func BlockTimestampIn(vs ...time.Time) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldIn(FieldBlockTimestamp, vs...))
}

// BlockTimestampNotIn applies the NotIn predicate on the "block_timestamp" field.
func BlockTimestampNotIn(vs ...time.Time) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldNotIn(FieldBlockTimestamp, vs...))
}

// BlockTimestampGT applies the GT predicate on the "block_timestamp" field.
func BlockTimestampGT(v time.Time) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldGT(FieldBlockTimestamp, v))
}

// BlockTimestampGTE applies the GTE predicate on the "block_timestamp" field.
func BlockTimestampGTE(v time.Time) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldGTE(FieldBlockTimestamp, v))
}

// BlockTimestampLT applies the LT predicate on the "block_timestamp" field.
func BlockTimestampLT(v time.Time) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldLT(FieldBlockTimestamp, v))
}

// BlockTimestampLTE applies the LTE predicate on the "block_timestamp" field.
func BlockTimestampLTE(v time.Time) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldLTE(FieldBlockTimestamp, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldContainsFold(FieldStatus, v))
}

// MatchedOrderIDEQ applies the EQ predicate on the "matched_order_id" field.
func MatchedOrderIDEQ(v int64) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldEQ(FieldMatchedOrderID, v))
}

// MatchedOrderIDNEQ applies the NEQ predicate on the "matched_order_id" field.
func MatchedOrderIDNEQ(v int64) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldNEQ(FieldMatchedOrderID, v))
}

// MatchedOrderIDIn applies the In predicate on the "matched_order_id" field.
func MatchedOrderIDIn(vs ...int64) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldIn(FieldMatchedOrderID, vs...))
}

// MatchedOrderIDNotIn applies the NotIn predicate on the "matched_order_id" field.
func MatchedOrderIDNotIn(vs ...int64) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldNotIn(FieldMatchedOrderID, vs...))
}

// MatchedOrderIDGT applies the GT predicate on the "matched_order_id" field.
func MatchedOrderIDGT(v int64) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldGT(FieldMatchedOrderID, v))
}

// MatchedOrderIDGTE applies the GTE predicate on the "matched_order_id" field.
func MatchedOrderIDGTE(v int64) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldGTE(FieldMatchedOrderID, v))
}

// MatchedOrderIDLT applies the LT predicate on the "matched_order_id" field.
func MatchedOrderIDLT(v int64) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldLT(FieldMatchedOrderID, v))
}

// MatchedOrderIDLTE applies the LTE predicate on the "matched_order_id" field.
func MatchedOrderIDLTE(v int64) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldLTE(FieldMatchedOrderID, v))
}

// MatchedOrderIDIsNil applies the IsNil predicate on the "matched_order_id" field.
func MatchedOrderIDIsNil() predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldIsNull(FieldMatchedOrderID))
}

// MatchedOrderIDNotNil applies the NotNil predicate on the "matched_order_id" field.
func MatchedOrderIDNotNil() predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldNotNull(FieldMatchedOrderID))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldContainsFold(FieldNotes, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.USDTDeposit) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.USDTDeposit) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.USDTDeposit) predicate.USDTDeposit {
	return predicate.USDTDeposit(sql.NotPredicates(p))
}
